### ISSUE TITLE
Multistep ahead forecast feature

### ISSUE THREAD

**Issue by RLstat** [sassoftware/python-dlpy#101]
Feedback from forecasting people that multi-step-ahead forecasting is pretty important. So I am thinking about building it in here. Probably with a method called `model.forecast()`. What it does is like:

![multi-step-ahead](https://user-images.githubusercontent.com/18621301/51617459-47fe0d80-1efa-11e9-8a95-08af2660b085.png)

If it makes sense, fits the theme and something good to have, I will start working on it for the next couple of weeks.

**Comment by ethem-kinginthenorth** [comment]
@RLstat I value your judgement on this subject. make the call.

**Comment by ethem-kinginthenorth** [comment]
@RLstat I am assuming you are implementing this right?

**Comment by RLstat** [comment]
@ethem-kinginthenorth , Yes, I am working on it.

**Comment by ethem-kinginthenorth** [comment]
@RLstat awesome. could you please give me an estimate when you can deliver this? I would like to plan the next release.

**Comment by RLstat** [comment]
@ethem-kinginthenorth Probably by the end of this month.

**Comment by ethem-kinginthenorth** [comment]
@RLstat thanks. I am waiting you to finish before doing another release. please keep me updated. thanks

**Comment by RLstat** [comment]
@ethem-kinginthenorth update: likely to have a merge request regarding this feature by the end of next week.

**Comment by RLstat** [comment]
closing this as the new feature has been merged.
