### ISSUE TITLE
ImageTable.show does not support an image variable not named _image_

### ISSUE THREAD

**Issue by xinmwu** [sassoftware/python-dlpy#103]
I have a CAS table with _id_, _label_ and _LayerAct_0_IMG_0_

I have create the image table 

data = ImageTable.from_table(outTbl3, image_col='_LayerAct_0_IMG_0_') 

however,  data.show(nimages=10, ncol=5, randomize=False) has errors about _image_ variable not found; data.show does not have an image option that parses in the image variable.

**Comment by sasxianhu** [comment]
Which DLPy version?

Best,
XQ

On Feb 4, 2019, at 9:44 AM, xinmwu <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

I have a CAS table with id, label and LayerAct_0_IMG_0

I have create the image table

data = ImageTable.from_table(outTbl3, image_col='LayerAct_0_IMG_0')

however, data.show(nimages=10, ncol=5, randomize=False) has errors about image variable not found; data.show does not have an image option that parses in the image variable.

**Comment by xinmwu** [comment]
It is 1.0.1

**Comment by ethem-kinginthenorth** [comment]
@xinmwu I am still cleaning up the hard codings from the very initial version. I will be adding this feature shortly.

**Comment by ethem-kinginthenorth** [comment]
@xinmwu I am about to push some changes. In order you to get these changes you have two options: 1) wait until the next release, hoping to have one late February or early March, or 2) git clone and point out to that version. 

When I push the code, this issue will be closed, if you still have issues. feel free to re-open it.

**Comment by ethem-kinginthenorth** [comment]
@xinmwu I just check the source code again and I believe you might have a different issue. I am looking into this.

**Comment by ethem-kinginthenorth** [comment]
I fixed this with another push. Seems like the problem was coming from a different place. I tested with a scenario very close to yours and it is working. But again, in order to get this change you should get a local copy or wait until the next release and do an update.
