### ISSUE TITLE
dlpy.ImageTable.load_files not working 

### ISSUE THREAD

**Issue by totuni** [sassoftware/python-dlpy#105]
`s.setsessopt(caslib='CASUSER')  #  Set default active caslib
#### this is located at /home/totuni/casuser/

panther='/data/totuni/images'
my_images = dlpy.ImageTable.load_files(s, path=panther)`

gives me the following error:  

> ERROR: Parameter 'caslib' is not recognized.
ERROR: Expecting one of the following: path, casOut, pathIsList, repeat, quiet, decode, recurse, labelLevels, distribution, addColumns, series, source, outputImages, outputImage, duplicate, silent, decompress.
ERROR: The action stopped due to errors.
ERROR: The file or path 'ImageData_SML6GP' is not available in the file system.
ERROR: Table 'ImageData_SML6GP' could not be loaded.
ERROR: Failure opening table 'ImageData_SML6GP': A table could not be loaded.
ERROR: The action stopped due to errors.

This worked once on dlpy .6 and when I upgraded it has never worked again.   I have placed my images on both the jupyter server and cas controller node.  I believe it should be able to find them.  

Thanks for the help.

**Comment by ethem-kinginthenorth** [comment]
what is the viya version?

**Comment by ethem-kinginthenorth** [comment]
the error sounds like the action does not recognize the caslib parameter which is added later. is there a way to check the same code on a very recent sas viya?

**Comment by totuni** [comment]
Is 8.2 V03 old?

**Comment by totuni** [comment]
I can run it on a RACE image  EEC164_V34_CL2 - but it runs to slow to be usable and the solvers don't work.  What version of SAS viya does dlpy support?

**Comment by sasxianhu** [comment]
3.4 should work.

Best,
XQ

On Feb 6, 2019, at 5:18 PM, Tom Tuning <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

I can run it on a RACE image EEC164_V34_CL2 - but it runs to slow to be usable and the solvers don't work. What version of SAS viya does dlpy support?

**Comment by ethem-kinginthenorth** [comment]
dlpy versions are aligned with SAS Viya versions. dlpy version >= 1.0.0 requires SAS Viya 3.4

**Comment by totuni** [comment]
Upgrading to Viya 3.4 solved the problem.
