### ISSUE TITLE
Tiny yolo weights

### ISSUE THREAD

**Issue by MsJellyKing** [sassoftware/python-dlpy#108]
Hi

How do I convert the tinyyolo weights file to sashdat?

Thanks
Kelly

**Comment by sasxianhu** [comment]
Which tinyyolo weights file?

**Comment by bensloane** [comment]
I think this is referring to model.deploy() to save the trained weights but if that is not that case please correct me. I would use the following:

```Python
yolo = Tiny_YoloV2(s,
                 n_classes=1, 
                 predictions_per_grid=5, 
                 anchors = train_anchors,
                 max_boxes=100, 
                 coord_type='yolo',
                 max_label_per_image = 100,
                 detection_threshold=0.2, 
                 iou_threshold=0.5)


yolo.fit(valid_table=valid, 
              data=train, 
              optimizer=optimizer, 
              data_specs=data_specs, 
              n_threads=4, 
              record_seed = 13309,
              force_equal_padding=True, 
              gpu= gpu
             )

yolo.deploy('/models/tiny-yolo-face/60/', output_format='table')
```
model.deploy() will write three sashdat files to that listed directory: the weights table, weight attribute table, and the model table. If you'd like to reload that model you can use the following snippet which points to the model table saved in the mentioned directory. 

```Python
 yolo = Model.from_sashdat(s, '/models/tiny-yolo-face/60/Tiny-Yolov2.sashdat')
```

**Comment by MsJellyKing** [comment]
Yes this worked. Thanks so much!

**Comment by ethem-kinginthenorth** [comment]
@MsJellyKing glad it worked. Can we close this issue if everything is great now :)

**Comment by MsJellyKing** [comment]
Yes please :D
