### ISSUE TITLE
Restricting the 'table' in model.train and 'data' in model.fit to be only CASTable object (not strings)?

### ISSUE THREAD

**Issue by RLstat** [sassoftware/python-dlpy#111]
I am wondering whether we want to restrict the `table` argument in `model.train` and `data` argument in `model.fit` to be CASTable object only (or its subclasses, such as ImageTable, TimeseriesTable, AudioTable etc. ), but not strings. 

There are several benefits: 
1) we can infer what type of input data we are dealing with, by checking whether it is `ImageTable`, `TimeseriesTable`, `AudioTable` or just regular `CASTable`. If we are allowing strings to indicate the name of the CASTable, we don't really know what type it is. One related issue is #52. Currently, we cannot use `model.evaluate` for cases where we are not using RNN (so the model_type='CNN' by default), and the input is not `ImageTable`, since it currently assumes if we are not using RNN, then the input has to be `ImageTable`. A lot of analysis scenarios don't meet this assumption, such as tabular data analysis. It can be solved, if we do a check for the input data type in model.train, so we can know what type of input we trained on when we evaluate (whether it is ImageTable or not). But if it is string, then we won't be able to do that. 
2) some of the table info can be passed on to the prediction stage. For example, while I am working on #101, I realize I need the information stored in TimeseriesTable object (in the form of its attributes) during training to determine how to do multi-step forecast. However, if we allow strings as input, then I lose all those info. 

Personally, I also feel passing CASTable object as input (which we already support) is more python oriented  than passing CASTable names (strings).

Drawbacks: compatible issues. Some of the tests and examples are using strings, so we may need to change that. 

Open for discussion, any thoughts?

**Comment by sasxianhu** [comment]
We should always allow the string since the table object is too strict. If your function need a table object, just check the type and return the error if the string is passed in.

**Comment by RLstat** [comment]
sounds good to me. Keeping it as it is and doing type checking on specific applications. Closing the issue.
