### ISSUE TITLE
Sharing weights between layers

### ISSUE THREAD

**Issue by kedarps** [sassoftware/python-dlpy#116]
Does `dlpy` allow sharing of weights between layers? I see this functionality in the `addLayer` action using the `sharingWeights` parameter in the `deepLearn` action set. 

I do not see this parameter in `dlpy.Layer`. Is there a way to share weights between layers in `dlpy`?

**Comment by sasxianhu** [comment]
Not with Viya 3.4. We will release a new Viya at 19w21. The APIs are designed for this new release.
