### ISSUE TITLE
Error loading from ONNX model

### ISSUE THREAD

**Issue by kedarps** [sassoftware/python-dlpy#121]
I am having issues loading onnx model. Here is the code:

```
import onnx
onnx_mdl = onnx.load('myFile.onnx')
model = Model.from_onnx_model(conn, onnx_model=onnx_mdl, output_model_table='loaded_model_from_onnx',  output_layer='f.c.1')
```

I get the following error:
![onnxImportError](https://user-images.githubusercontent.com/12261096/55172511-86a98180-5150-11e9-81d5-c8638eb38b68.PNG)

My `onnx` version is `1.1.1`.

**Comment by yg2288** [comment]
Hi, this error is due to an older version of ONNX; DLPy supports ONNX version 1.3 or newer ([doc here](https://sassoftware.github.io/python-dlpy/generated/dlpy.model.Model.deploy.html?highlight=onnx)) - could you try upgrading and see if the issue persists?  Thanks

**Comment by kedarps** [comment]
I successfully updated onnx to 1.4.1 and I am able to use `from_onnx_model`, but I am stuck on the next step using `load_weights`.

Running, 
```
onnx_mdl = onnx.load('myPath/siamese_cnn_branch1.onnx')
model = Model.from_onnx_model(conn, onnx_model=onnx_mdl)
```
gives me,
```
NOTE: Successfully written weights file as U:\myPath\onnx_model_64OKmg_weights.onnxmodel.h5
NOTE: Model table is attached successfully!
NOTE: Model is named to "onnx_model_64okmg" according to the model name in the table.
NOTE: Successfully imported ONNX model.
```

I am trying to load the weights from `h5` file, `model.load_weights('onnx_model_64OKmg_weights.onnxmodel.h5')`. I get an error,

![loadWeightsError](https://user-images.githubusercontent.com/12261096/55187962-946eff00-5170-11e9-8853-2103b5bf631e.PNG)

I have seen the tutorial video, where `attrtable` is specified when calling `load_weights`, but an attribute table was not generated when I exported the model using  `model.deploy('myPath', output_format='onnx')`

Amy help would be appreciated. Thanks.

**Comment by ethem-kinginthenorth** [comment]
I am seeing two issues here, one in the code and the second is in your side.
in the code: the code assumes that the path cannot be in the root, which is a fairly good assumption but I will investigate this.
in your code: please make sure that the path is accessible from your server.

**Comment by kedarps** [comment]
I tried the following: I copied the `.h5` file to the server. I have the server path added using the `addcaslib` action. I still get the same error.

**Comment by ethem-kinginthenorth** [comment]
please use the full path of your file. the goal is that you don't need to worry about the caslib where dlpy takes care of it under the hood.

**Comment by kedarps** [comment]
Providing the full path gives me a duplicate caslib error. Note that the path with my weights file is not the same as my `caslib` path. 

![caslibError](https://user-images.githubusercontent.com/12261096/55192149-3a733700-517a-11e9-9e15-5468341101c8.PNG)

This is on `U drive`. So I also tried using `/u/myPath/weights.h5` and `U:/myPath/weights.h5`

**Comment by sasxianhu** [comment]
Do not use your u drive.

**Comment by kedarps** [comment]
This is working now. Thanks for the help.
