### ISSUE TITLE
general question about "from_sashdat" method

### ISSUE THREAD

**Issue by haghad** [sassoftware/python-dlpy#125]
Can someone please point me to an example usage of the "from_sashdat" method for loading a model?

**Comment by sasxianhu** [comment]
After you generate a model and then call table.save and store it as a sashdat, you can call this API to load the model.

XQ

**Comment by haghad** [comment]
Thanks, for future readers of this post:
```
from dlpy import model
from dlpy.model import Model
model = Model.from_sashdat(conn, path="/path/to/model/my_model.sashdat", output_model_table="my_model")
```
