### ISSUE TITLE
general question about display_object_detections

### ISSUE THREAD

**Issue by haghad** [sassoftware/python-dlpy#126]
regarding ```display_object_detections``` method
Is there an option to only show predictions of a particular class?
For example, show predictions of detection_class="Person".
(So that for every image bounding boxes are drawn for predicted objects of type person but not for predicted objects of any other type.)

**Comment by sasxianhu** [comment]
Do not think so.

**Comment by ethem-kinginthenorth** [comment]
@haghad you can achieve something similar by filtering the resulting detection table (e.g., where='_Object0_=="Person"').

That said, if you think this is an important for this and future projects of yours, we can mark this as 'future'.

Please let us know. 

Thanks

**Comment by ethem-kinginthenorth** [comment]
@haghad can we close this issue? do you have any further questions?

**Comment by ethem-kinginthenorth** [comment]
@haghad closing the issue. if you have any further questions, please open a new one, or re-open this one. thanks
