### ISSUE TITLE
Locale problem on multi platform setting

### ISSUE THREAD

**Issue by pkaczynski** [sassoftware/python-dlpy#135]
There is an issue in `create_object_detection_table` when using CAS server with different locale than  the client. TXT files are loaded using client locale even when data resides on the serever.

[This line](https://github.com/sassoftware/python-dlpy/blob/590141d64fc3933fd8d053731bc63cb867e7965f/dlpy/utils.py#L1246) loads the data as varchar, even if the contents are numbers with a dot as a decimal separator (en_US locale on the  server). This is probably because my client locale has a comma as a decimal separator.

Please change this to use server side locale or give a possibility to pass this locale to the function. Or fix the locale as en_US as a workaround.

**Comment by ethem-kinginthenorth** [comment]
@wenyushi can you please take a look at this.

**Comment by wenyushi** [comment]
Sure, I will look into it.

**Comment by ethem-kinginthenorth** [comment]
@wenyushi any update on this ? thanks

**Comment by wenyushi** [comment]
I am not very familiar with the locale problem, and I am wondering if we are able to specify the locale of a session. Need more time to fix it.

**Comment by ethem-kinginthenorth** [comment]
I am tagging this as future / feature request to see if we have any cycle to address this

**Comment by sasxianhu** [comment]
I am working on this.
