### ISSUE TITLE
Attempting to create multipath network

### ISSUE THREAD

**Issue by User1542** [sassoftware/python-dlpy#138]
The following is giving me an error I don’t know how to resolve. Any ideas?

inLayer = Input(n_channels = 3,width=32, height=128, offsets=myimage.channel_means, 
                      name='input1', random_mutation='random', random_flip='HV')
conv1 = Conv2d(32, 3, 3, name='conv1', act='relu', init='msra')([inLayer])
conv2 = Conv2d(32, 5, 5, name='conv2', act='relu', init='msra')([inLayer])
fc1 = Dense(3, name='fc1')([conv1])
fc2 = Dense(3, name='fc2')([conv2])
res = Res(name='res1')([fc1, fc2])
outLayer = OutputLayer(n=3, name='output')([res])

TypeError                                 Traceback (most recent call last)
<ipython-input-43-20a86442515c> in <module>()
      5 fc1 = Dense(3, name='fc1')([conv1])
      6 fc2 = Dense(3, name='fc2')([conv2])
----> 7 res = Res(name='res1')([fc1, fc2])
      8 outLayer = OutputLayer(n=3, name='output')([res])

~\python-dlpy\dlpy\layers.py in __call__(self, inputs)
    240             self._inbound_nodes = Node(self.src_layers, self)
    241             self.tensor = Tensor(self)  # return Tensor object
--> 242             self.tensor.shape = self.output_size
    243         return self.tensor
    244 

~\python-dlpy\dlpy\layers.py in output_size(self)
   1028             if self.src_layers is None:
   1029                 self._output_size = (0, 0, 0)
-> 1030             self._output_size = (int(min([item.output_size[0] for item in self.src_layers])),
   1031                                  int(min([item.output_size[1] for item in self.src_layers])),
  1032                                  int(max([item.output_size[2] for item in self.src_layers])))

~\python-dlpy\dlpy\layers.py in <listcomp>(.0)
   1028             if self.src_layers is None:
   1029                 self._output_size = (0, 0, 0)
-> 1030             self._output_size = (int(min([item.output_size[0] for item in self.src_layers])),
   1031                                  int(min([item.output_size[1] for item in self.src_layers])),
   1032                                  int(max([item.output_size[2] for item in self.src_layers])))

TypeError: 'int' object is not subscriptable

**Comment by wenyushi** [comment]
Each tensor will be assigned a shape based on its source layer(s). In the case, the shape of tensor 'res' is derived from the output size of dense layers. Res layer can only receive 3 dimension tensor inputs while Dense layer outputs 1-d tensor. So, the error line cannot find second and third dimension, I will fix the issue in my next push. Thanks.
