### ISSUE TITLE
Loading pre-trained model from .sashdat table file error 

### ISSUE THREAD

**Issue by carolinepotts** [sassoftware/python-dlpy#140]
I am trying to load a model from a .sashdat table file using the following lines of code:

model5 = Model(sess)
model_file = '/disk/linux/dlpy/vgg16.sashdat'
model5.load(path=model_file)

I am getting the following error: 
![image](https://user-images.githubusercontent.com/29736845/58107500-f91a6900-7bb7-11e9-8f61-6223fad15dc0.png)

I recently installed dlpy using pip.

**Comment by ethem-kinginthenorth** [comment]
@wenyushi would you please take a look at this. Thanks

**Comment by wenyushi** [comment]
@carolinepotts Would you mind sharing the sashdat or the script that generates the model? Thanks.

**Comment by carolinepotts** [comment]
@wenyushi It is actually one of the example notebooks - the one called A_Comprehensive_Image_Classification_Example in the quick_start folder

**Comment by wenyushi** [comment]
After vb015, we add padding_width, height, top and left as properties in the convolution and pooling layer. The model in the test case was generated before the change. Anyway, in order to be compatible with old Viya release, I will push a fix to check the existing of the properties.

**Comment by ethem-kinginthenorth** [comment]
@wenyushi I believe this is resolved, right? are we ready to close this issue?

**Comment by wenyushi** [comment]
Yes, please close it.
