### ISSUE TITLE
Unittest test_imagescaler1 error with onnx 1.5.0

### ISSUE THREAD

**Issue by carolinepotts** [sassoftware/python-dlpy#141]
The unittest test_imagescaler1 gives an error (OnnxParseError: Unable to determine the number of neurons in FC layer) when onnx 1.5.0 is used.  

When onnx 1.4.1 is used, the test passes.

**Comment by ethem-kinginthenorth** [comment]
@yg2288 could you please take a look at this issue. Seems like something is not working with a version change.

**Comment by yg2288** [comment]
Thanks - I'm looking into this issue.

**Comment by yg2288** [comment]
This error occurs because ImageScaler was removed in ONNX 1.5.0.  It was an experimental operator in earlier versions, and the latest version removed all experimental ops. I will open a pull request to fix this issue.

**Comment by ethem-kinginthenorth** [comment]
@yg2288 how we doing on this issue? thanks
