### ISSUE TITLE
Label files not properly parsed when using different OSes

### ISSUE THREAD

**Issue by ang-zy** [sassoftware/python-dlpy#143]
I'm using a Windows client with a Linux CAS server. Images are stored on the server, while labels are stored on the client machine. Labels and images are also stored in different directory structures (Images in `VOC2012/Images` and labels in `VOC2012/Annotations`). When I run `dlpy.utils.create_object_detection_table`, I get a `DLPyError: Can not find any xml file under data_path` (Stack trace included at the bottom).

The error occurs because `label_files` are populated with the list of files in the server's path when it is passed to `get_txt_annotations`. This causes `get_txt_annotations` to search the server's directory instead of the client machine's directory. https://github.com/sassoftware/python-dlpy/blob/a9dc063ac457ae996f48f8cf7fbf2ef0b5a227ee/dlpy/utils.py#L1232-L1238.

```
---------------------------------------------------------------------------
DLPyError                                 Traceback (most recent call last)
<ipython-input-2-a522784f5469> in <module>
      1 import dlpy #dlpy has a further sub-library called utils, accessible by dlpy.utils
      2 dlpy.utils.create_object_detection_table(casServer, data_path = imagesPath, local_path = annotationsPath,
----> 3                                          coord_type = 'yolo', output = 'detectionTable')
      4 #dlpy.utils.display_object_detections(casServer, 'detectionTable', 'yolo', max_objects=3, num_plot=6, n_col=3)

c:\program files\python37\lib\site-packages\dlpy\utils.py in create_object_detection_table(conn, data_path, coord_type, output, local_path, image_size)
   1231     # parse xml or json files and create txt files
   1232     if need_to_parse:
-> 1233         get_txt_annotation(local_path, coord_type, image_size, label_files)
   1234 
   1235     label_tbl_name = random_name('obj_det')

c:\program files\python37\lib\site-packages\dlpy\utils.py in get_txt_annotation(local_path, coord_type, image_size, label_files)
   1096     label_files = [x for x in label_files if x.endswith('.xml')]
   1097     if len(label_files) == 0:
-> 1098         raise DLPyError('Can not find any xml file under data_path')
   1099     for idx, filename in enumerate(label_files):
   1100         _convert_xml_annotation(filename, coord_type, image_size)

DLPyError: Can not find any xml file under data_path
```

**Comment by wenyushi** [comment]
Hi, local_path and data_path should point to the same location and data_path specifies a location where annotation files and image files are stored. The XML files will be parsed on your client side and stored in TXT format in the same directory which can also be accessed by your server. In your case, you mentioned that you have different directories for label and image. Please put them in the same directory.

**Comment by ang-zy** [comment]
So for this function to work, both annotation and image files must be stored in a single directory, and this directory must be accessible by both server and client machines?

**Comment by wenyushi** [comment]
Correct.
