### ISSUE TITLE
NameError: name 'bias_term' is not defined

### ISSUE THREAD

**Issue by Mespith** [sassoftware/python-dlpy#163]
I'm trying to import the open pose Caffe model to SAS. I have the .prototxt and .caffemodel files so I should be able to use the dlpy.Model.from_caffe_model to create a .hdf5 file, right?

Python 3.6.8
swat 1.5.1
dlpy 1.0.2

After I apply the workaround described in #120 and run the line below I get an error.
`model = dlpy.Model.from_caffe_model(sess, '/mnt/c/Users/SNLJDK/Caffe/pose_deploy.prototxt', output_model_table=dict(name="body_25", caslib="casuser"), model_weights_file='/mnt/c/Users/SNLJDK/Caffe/pose_iter_584000.caffemodel')`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jaimy/anaconda3/envs/caffepy/lib/python3.6/site-packages/dlpy/network.py", line 389, in from_caffe_model
    output_code = caffe_to_sas(input_network_file, model_name, network_param = model_weights_file, **kwargs)
  File "/home/jaimy/anaconda3/envs/caffepy/lib/python3.6/site-packages/dlpy/model_conversion/sas_caffe_parse.py", line 190, in caffe_to_sas
    sas_code = caffe_convolution_layer(clayer, model_name)
  File "/home/jaimy/anaconda3/envs/caffepy/lib/python3.6/site-packages/dlpy/model_conversion/sas_caffe_parse.py", line 402, in caffe_convolution_layer
    if (bias_term is not None):
NameError: name 'bias_term' is not defined

**Comment by eusdougc** [comment]
@Mespith: as @ethem-kinginthenorth noted on #120, there has not been an official release of DLPy that includes a number of fixes for Caffe model conversion.  Please try cloning the repository to pick up these changes and try again.  If you still have problems, please post a link to the prototxt file and caffemodel file you are using.

**Comment by Mespith** [comment]
Thank you @eusdougc  and @ethem-kinginthenorth I've cloned the repository and am using sas-dlpy-1.0.3.dev0 and the mentioned problems are indeed gone. I do get another error now which I hope you can help me with as well.

This is the link to the .prototxt file I'm using:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/models/pose/body_25

The .caffemodel file I got by running getModels.bat in the model folder of the repository.

Convolution layer requires one input layer, 0 provided
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jaimy/anaconda3/envs/caffepy/lib/python3.6/site-packages/dlpy/network.py", line 416, in from_caffe_model
    exec(output_code)
TypeError: exec() arg 1 must be a string, bytes or code object

**Comment by sasxianhu** [comment]
Note not all of the layers from Caffe can be supported by SAS and vice versa.

Best,
XQ

On Jul 10, 2019, at 4:30 PM, Jaimy <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

Thank you @eusdougc<https://github.com/eusdougc> and @ethem-kinginthenorth<https://github.com/ethem-kinginthenorth> I've cloned the repository and am using sas-dlpy-1.0.3.dev0 and the mentioned problems are indeed gone. I do get another error now which I hope you can help me with as well.

This is the link to the .prototxt file I'm using:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/master/models/pose/body_25

The .caffemodel file I got by running getModels.bat in the model folder of the repository.

Convolution layer requires one input layer, 0 provided
Traceback (most recent call last):
File "", line 1, in
File "/home/jaimy/anaconda3/envs/caffepy/lib/python3.6/site-packages/dlpy/network.py", line 416, in from_caffe_model
exec(output_code)
TypeError: exec() arg 1 must be a string, bytes or code object

**Comment by Mespith** [comment]
Ah yes, I was afraid of this. I wonder which layer it is then. Maybe the PReLU activation in the convolution layer?

**Comment by eusdougc** [comment]
The problem you are currently having is due to the input definition in the prototxt file.  If you replace

input: "image"
input_dim: 1 # This value will be defined at runtime
input_dim: 3
input_dim: 16 # This value will be defined at runtime
input_dim: 16 # This value will be defined at runtime

with something like this

layer {
  name: "image"
  type: "MemoryData"
  top: "image"
  memory_data_param {
    batch_size: 10   # this should be the batch size you want
    channels: 3
    height: 16         # this should be the actual height of the images you are using
    width: 16          # this should be the actual width of the images you are using
  }
}

you should get past the error you are seeing.  However, you will get another error later on with the PRELU activation function.  We do not currently support it.

**Comment by Mespith** [comment]
Thank you for the input definition help. I still think there is a problem there:

F0710 14:45:57.140903   143 layer.hpp:364] Check failed: ExactNumTopBlobs() == top.size() (2 vs. 1) MemoryData Layer produces 2 top blob(s) as output.

**Comment by eusdougc** [comment]
You are correct, I missed a line:

layer {
name: "image"
type: "MemoryData"
top: "image"
**top: "label"**
memory_data_param {
batch_size: 10 # this should be the batch size you want
channels: 3
height: 16 # this should be the actual height of the images you are using
width: 16 # this should be the actual width of the images you are using
}
}

**Comment by Mespith** [comment]
Yes indeed. It works with that extra line! I get an error saying that the prelu is not known:

Unknown Caffe activation function = prelu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jaimy/anaconda3/envs/caffepy/lib/python3.6/site-packages/dlpy/network.py", line 416, in from_caffe_model
    exec(output_code)
TypeError: exec() arg 1 must be a string, bytes or code object

Thank you for all the help. I will try another model until PReLU will be supported :)

**Comment by ethem-kinginthenorth** [comment]
You can also replace prelu with something else.
Is that that crucial for the model?
Thanks
Ethem

**Comment by ethem-kinginthenorth** [comment]
You can also replace prelu with something else.
Is that that crucial for the model?

**Comment by Mespith** [comment]
I don't really know. Can you easily swap PReLU with something else? I understand that it's like Leaky ReLU but with a parameter that indicates the "leakiness". This parameter will be stored in the .caffemodel file, right? Would it still work? Worth checking out I guess

**Comment by Mespith** [comment]
So, I tried replacing all PReLU activations with ReLU. But I think the parameters that should be used by the PReLU function are causing the following error:

F0710 15:14:48.002986   303 net.cpp:750] Check failed: target_blobs.size() == source_layer.blobs_size() (0 vs. 1) Incompatible number of blobs for layer prelu4_2

**Comment by sasxianhu** [comment]
I don’t think PRELU will work. We actually support leaky RELU but the parameter is fixed. It might work if the learned parameter is close to 0.01.

Best,
XQ

On Jul 10, 2019, at 10:16 PM, Jaimy <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

So, I tried replacing all PReLU activations with ReLU. But I think the parameters that should be used by the PReLU function are causing the following error:

F0710 15:14:48.002986 303 net.cpp:750] Check failed: target_blobs.size() == source_layer.blobs_size() (0 vs. 1) Incompatible number of blobs for layer prelu4_2

**Comment by Mespith** [comment]
Yeah but even then. If you set the parameter of the Leaky ReLU then it will still try to but the parameter in the .caffemodel file somewhere where it doesn't fit.

**Comment by ethem-kinginthenorth** [comment]
I believe we do not support prelu in the server side, @sasxianhu can you please confirm this?

**Comment by sasxianhu** [comment]
We don’t support prelu only leaky relu.

Best,
XQ

On Jul 19, 2019, at 1:42 PM, ethem-kinginthenorth <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

I believe we do not support prelu in the server side, @sasxianhu<https://github.com/sasxianhu> can you please confirm this?

**Comment by ethem-kinginthenorth** [comment]
thanks @sasxianhu , then we cannot really import this model that has the prelu.

**Comment by ethem-kinginthenorth** [comment]
@Mespith I am assuming there is not much we can fix through DLPy for this specific case. Is it OK to close this issue?

**Comment by ethem-kinginthenorth** [comment]
@Mespith I am closing this issue, please feel free to re-open or open another one if you have any further questions. Thanks
