### ISSUE TITLE
sashdat data for segmentation example

### ISSUE THREAD

**Issue by Kaynelua** [sassoftware/python-dlpy#168]
Hello, is it possible to provide a link to the sashdat file used in the segmentation example, i.e "soccer_player/sgf_256.sashdat". Would like to test out the segmentation example. 

Thank you!

**Comment by ethem-kinginthenorth** [comment]
I added a small version of the example (I didn't want to make this project giant) here: tests/datasources/sgf_256_small.sashdat). It is the same file with less number of samples.

**Comment by Kaynelua** [comment]
Thanks @ethem-kinginthenorth, will it be also be possible to provide a guide on how the sashdat should be constructed / formatted ? We are interns from SAS trying to implement segmentation on other applications. Thanks!

**Comment by dxq77dxq** [comment]
The easiest way would be to use ImageTable.load_files() to load both the raw images and ground truth images to two sashdat, and then use dljoin() to combine them into one using a unique id (for example, file name).
