### ISSUE TITLE
Error after updated to v1.1.0

### ISSUE THREAD

**Issue by joyozhang** [sassoftware/python-dlpy#169]
model.fit(data='train_bind', optimizer=optimizer, force_equal_padding = True, record_seed = 13309,data_specs=data_specs,
          seed=13309, n_threads=5)
--------------------------------------------------------------------------------------------------------
NOTE: Training based on existing weights.
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
/opt/sas/python/lib/python3.7/site-packages/swat/cas/rest/connection.py in invoke(self, action_name, kwargs)
    433         try:
--> 434             self._results = json.loads(a2u(res, 'utf-8'), strict=False)
    435             if self._results.get('disposition', None) is None:

/opt/sas/python/lib/python3.7/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    360         kw['parse_constant'] = parse_constant
--> 361     return cls(**kw).decode(s)

/opt/sas/python/lib/python3.7/json/decoder.py in decode(self, s, _w)
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()

/opt/sas/python/lib/python3.7/json/decoder.py in raw_decode(self, s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

SWATError                                 Traceback (most recent call last)
<ipython-input-54-c973c064708c> in <module>
      1 model.fit(data='train_bind_cz', optimizer=optimizer, force_equal_padding = True, record_seed = 13309,data_specs=data_specs,
----> 2           seed=13309, n_threads=5)

/opt/sas/python/lib/python3.7/site-packages/dlpy/model.py in fit(self, data, inputs, target, data_specs, mini_batch_size, max_epochs, log_level, lr, optimizer, nominals, texts, target_sequence, sequence, text_parms, valid_table, valid_freq, gpu, attributes, weight, seed, record_seed, missing, target_missing, repeat_weight_table, force_equal_padding, save_best_weights, n_threads, target_order)
    279                        force_equal_padding=force_equal_padding, init_weights=init_weights, target_order=target_order,
    280                        best_weights=self.best_weights, model=self.model_table, n_threads=n_threads,
--> 281                        model_weights=dict(replace=True, **self.model_weights.to_table_params()))
    282 
    283         try:

/opt/sas/python/lib/python3.7/site-packages/dlpy/model.py in train(self, table, attributes, inputs, nominals, texts, valid_table, valid_freq, model, init_weights, model_weights, target, target_sequence, sequence, text_parms, weight, gpu, seed, record_seed, missing, optimizer, target_missing, best_weights, repeat_weight_table, force_equal_padding, data_specs, n_threads, target_order)
    679                               target_order=target_order)
    680 
--> 681         rt = self._retrieve_('deeplearn.dltrain', message_level='note', **parameters)
    682 
    683         if rt.severity < 2:

/opt/sas/python/lib/python3.7/site-packages/dlpy/network.py in _retrieve_(self, _name_, message_level, **kwargs)
    253     def _retrieve_(self, _name_, message_level='error', **kwargs):
    254         ''' Call a CAS action '''
--> 255         return self.conn.retrieve(_name_, _messagelevel=message_level, **kwargs)
    256 
    257     @classmethod

/opt/sas/python/lib/python3.7/site-packages/swat/cas/connection.py in retrieve(self, _name_, **kwargs)
   1690         try:
   1691             # Call the action and compile the results
-> 1692             signature = self._invoke_with_signature(a2n(_name_), **kwargs)
   1693             results = self._get_results(getnext(self, datamsghandler=datamsghandler),
   1694                                         responsefunc=responsefunc, resultfunc=resultfunc)

/opt/sas/python/lib/python3.7/site-packages/swat/cas/connection.py in _invoke_with_signature(self, _name_, **kwargs)
   1169             self._merge_param_args(signature.get('params', {}), kwargs, action=_name_)
   1170 
-> 1171         self._invoke_without_signature(_name_, **kwargs)
   1172 
   1173         return signature

/opt/sas/python/lib/python3.7/site-packages/swat/cas/connection.py in _invoke_without_signature(self, _name_, **kwargs)
    943         '''
    944         if isinstance(self._sw_connection, rest.REST_CASConnection):
--> 945             errorcheck(self._sw_connection.invoke(a2n(_name_), kwargs),
    946                        self._sw_connection)
    947         else:

/opt/sas/python/lib/python3.7/site-packages/swat/cas/rest/connection.py in invoke(self, action_name, kwargs)
    439                     raise SWATError('Unknown error')
    440         except ValueError as exc:
--> 441             raise SWATError(str(exc))
    442 
    443         return self

SWATError: Expecting value: line 1 column 1 (char 0)

**Comment by ethem-kinginthenorth** [comment]
seems like connection is crashing. I dont think this is related with version upgrade. that said, a little bit more information would be great. I will follow up with you to see if we can get more data to debug the issue

**Comment by ethem-kinginthenorth** [comment]
can you please set "swat.options.cas.debug.responses = True" on top of your notebook and share the debug notes printed after the call you are getting the error. This statement should enable the debugging and let us know all the parameters sent to the server. In this way, we can analyze it further. thanks

**Comment by sasxianhu** [comment]
If you use the REST way to connect CAS, you have to git clone swat.

**Comment by joyozhang** [comment]
@ethem-kinginthenorth 
Thank you for the help. I have tried the debug option you provided. hope this log works for you guys.
---------------------------------------------------------------------
{
  "status": 0,
  "log": "",
  "results":   {
        "ColumnInfo": 
          {
            "_ctb": true,
            "label": "",
            "title": "Column Information for TRAIN_CZ3 in Caslib CASUSER(sasboot)",
            "name": "ColumnInfo",
            "schema": [
              { "name": "Column","label": "","format": "","type": "string","width": 15,"attributes": 
              {}
               },
              { "name": "ID","label": "","format": "","type": "int","width": 8,"attributes": 
              {}
               },
              { "name": "Type","label": "","format": "","type": "string","width": 9,"attributes": 
              {}
               },
              { "name": "RawLength","label": "","format": "","type": "int","width": 4,"attributes": 
              {}
               },
              { "name": "FormattedLength","label": "","format": "","type": "int","width": 4,"attributes": 
              {}
               },
              { "name": "Format","label": "","format": "","type": "string","width": 1,"attributes": 
              {}
               },
              { "name": "NFL","label": "","format": "","type": "int","width": 4,"attributes": 
              {}
               },
              { "name": "NFD","label": "","format": "","type": "int","width": 4,"attributes": 
              {}
               }
            ],
            "attributes": 
            {
              "Action": { "type": "string", "value": "columnInfo" },
              "Actionset": { "type": "string", "value": "table" },
              "CreateTime": { "type": "double", "value": 1879133553.70962 }
            },
            "rows": [
              [ "idjoin", 1, "char", 7, 7, "", 0, 0 ],
              [ "_image_", 2, "varbinary", 132394, 132394, "", 0, 0 ],
              [ "_Object0_", 3, "varchar", 3, 8, "$", 8, 0 ],
              [ "_Object1_", 4, "varchar", 3, 8, "$", 8, 0 ],
              [ "_Object0_x", 5, "double", 8, 12, "", 0, 0 ],
              [ "_Object1_x", 6, "double", 8, 12, "", 0, 0 ],
              [ "_Object0_y", 7, "double", 8, 12, "", 0, 0 ],
              [ "_Object1_y", 8, "double", 8, 12, "", 0, 0 ],
              [ "_Object0_width", 9, "double", 8, 12, "", 0, 0 ],
              [ "_Object1_width", 10, "double", 8, 12, "", 0, 0 ],
              [ "_Object0_height", 11, "double", 8, 12, "", 0, 0 ],
              [ "_Object1_height", 12, "double", 8, 12, "", 0, 0 ],
              [ "_nObjects_", 13, "double", 8, 12, "", 0, 0 ]
            ]
          }
      },
  "logEntries": [
  ],
  "disposition": {
    "severity": "Normal",
    "reason": "OK",
    "statusCode": 0,
    "formattedStatus": null,
    "debugInfo": null
  },
  "changedResources": [
    "caslibPermissions"  ],
  "metrics": {
    "elapsedTime": 0.00071,
    "cpuUserTime": 0.000689,
    "cpuSystemTime": 0,
    "systemTotalMemory": 515493523456,
    "systemNodes": 1,
    "systemCores": 32,
    "memory": 734912,
    "osMemory": 88145920,
    "systemMemory": 0,
    "memoryQuota": 6262202368,
    "ioPageReclaims": 0,
    "ioPageFaults": 0,
    "ioReadFaults": 0,
    "ioReadBlocks": 0,
    "ioReadCalls": 0,
    "ioWriteCalls": 0,
    "ioReadBytes": 0,
    "ioWriteBytes": 0,
    "ioWriteBytesCancelled": 0,
    "voluntaryContextSwitches": 0,
    "involuntaryContextSwitches": 0,
    "dataMovementBytes": 0
  }
}

{
  "status": 0,
  "log": "",
  "results":   {
        "TableInfo": 
          {
            "_ctb": true,
            "label": "",
            "title": "Table Information for Caslib CASUSER(sasboot)",
            "name": "TableInfo",
            "schema": [
              { "name": "Name","label": "","format": "","type": "string","width": 42,"attributes": 
              {}
               },
              { "name": "Rows","label": "","format": "","type": "int","width": 8,"attributes": 
              {}
               },
              { "name": "Columns","label": "","format": "","type": "int","width": 8,"attributes": 
              {}
               },
              { "name": "IndexedColumns","label": "Indexed Columns","format": "","type": "int","width": 8,"attributes": 
              {}
               },
              { "name": "Encoding","label": "","format": "","type": "string","width": 12,"attributes": 
              {}
               },
              { "name": "CreateTimeFormatted","label": "Created","format": "","type": "string","width": 25,"attributes": 
              {}
               },
              { "name": "ModTimeFormatted","label": "Last Modified","format": "","type": "string","width": 25,"attributes": 
              {}
               },
              { "name": "AccessTimeFormatted","label": "Last Accessed","format": "","type": "string","width": 25,"attributes": 
              {}
               },
              { "name": "JavaCharSet","label": "Character Set","format": "","type": "string","width": 31,"attributes": 
              {}
               },
              { "name": "CreateTime","label": "","format": "","type": "double","width": 8,"attributes": 
              {}
               },
              { "name": "ModTime","label": "","format": "","type": "double","width": 8,"attributes": 
              {}
               },
              { "name": "AccessTime","label": "","format": "","type": "double","width": 8,"attributes": 
              {}
               },
              { "name": "Global","label": "","format": "","type": "int","width": 4,"attributes": 
              {
                "Boolean": { "type": "string", "value": "Y" }
              }
               },
              { "name": "Repeated","label": "","format": "","type": "int","width": 4,"attributes": 
              {
                "Boolean": { "type": "string", "value": "Y" }
              }
               },
              { "name": "View","label": "","format": "","type": "int","width": 4,"attributes": 
              {
                "Boolean": { "type": "string", "value": "Y" }
              }
               },
              { "name": "SourceName","label": "Loaded Source","format": "","type": "string","width": 0,"attributes": 
              {}
               },
              { "name": "SourceCaslib","label": "Source Caslib","format": "","type": "string","width": 0,"attributes": 
              {}
               },
              { "name": "Compressed","label": "","format": "","type": "int","width": 4,"attributes": 
              {
                "Boolean": { "type": "string", "value": "Y" }
              }
               },
              { "name": "Creator","label": "Table Creator","format": "","type": "string","width": 7,"attributes": 
              {}
               },
              { "name": "Modifier","label": "Last Table Modifier","format": "","type": "string","width": 0,"attributes": 
              {}
               },
              { "name": "SourceModTimeFormatted","label": "Source Modified","format": "","type": "string","width": 0,"attributes": 
              {}
               },
              { "name": "SourceModTime","label": "","format": "","type": "double","width": 8,"attributes": 
              {}
               }
            ],
            "attributes": 
            {
              "Action": { "type": "string", "value": "tableInfo" },
              "Actionset": { "type": "string", "value": "table" },
              "CreateTime": { "type": "double", "value": 1879133554.07438 }
            },
            "rows": [
              [ "TRAIN_CZ3", 302, 13, 0, "utf-8", "2019-07-19T05:10:16+00:00", "2019-07-19T05:10:16+00:00", "2019-07-19T05:12:39+00:00", "UTF8", 1879132215.84964, 1879132215.84964, 1879132358.70106, 0, 0, 0, "", "", 0, "sasboot", "", "", null ],
              [ "_PY_T_FD8CE797_6316_4605_B1B5_FCE22D2CF5A1", 6, 13, 0, "utf-8", "2019-07-19T05:12:12+00:00", "2019-07-19T05:12:12+00:00", "2019-07-19T05:12:13+00:00", "UTF8", 1879132331.81127, 1879132331.81127, 1879132332.95066, 0, 0, 0, "", "", 0, "sasboot", "", "", null ],
              [ "TINY-YOLOV2", 334, 5, 0, "utf-8", "2019-07-19T05:12:37+00:00", "2019-07-19T05:12:37+00:00", "2019-07-19T05:12:39+00:00", "UTF8", 1879132357.04386, 1879132357.04386, 1879132358.70114, 0, 0, 0, "", "", 0, "sasboot", "", "", null ],
              [ "TINY-YOLOV2_WEIGHTS", 11037040, 3, 0, "utf-8", "2019-07-19T05:29:12+00:00", "2019-07-19T05:29:12+00:00", "2019-07-19T05:29:12+00:00", "UTF8", 1879133351.67038, 1879133351.67038, 1879133351.67038, 0, 0, 0, "", "", 0, "sasboot", "", "", null ]
            ]
          }
      },
  "logEntries": [
  ],
  "disposition": {
    "severity": "Normal",
    "reason": "OK",
    "statusCode": 0,
    "formattedStatus": null,
    "debugInfo": null
  },
  "changedResources": [
    "caslibPermissions"  ],
  "metrics": {
    "elapsedTime": 0.000886,
    "cpuUserTime": 0.000829,
    "cpuSystemTime": 0,
    "systemTotalMemory": 515493523456,
    "systemNodes": 1,
    "systemCores": 32,
    "memory": 707648,
    "osMemory": 88145920,
    "systemMemory": 0,
    "memoryQuota": 6262202368,
    "ioPageReclaims": 0,
    "ioPageFaults": 0,
    "ioReadFaults": 0,
    "ioReadBlocks": 0,
    "ioReadCalls": 0,
    "ioWriteCalls": 0,
    "ioReadBytes": 0,
    "ioWriteBytes": 0,
    "ioWriteBytesCancelled": 0,
    "voluntaryContextSwitches": 0,
    "involuntaryContextSwitches": 0,
    "dataMovementBytes": 0
  }
}

NOTE: Training based on existing weights.

**Comment by joyozhang** [comment]
@sasxianhu  
Do you mean install swat from git and import it?
I had a try and got same Error.

**Comment by sasxianhu** [comment]
In your error, does it report the swat path you created for git clone?

**Comment by kesmit13** [comment]
Unfortunately, I don't think we're going to be able to see anything from this JSON output because it looks like the result from the server is empty.  So it may be printing it here, but there is nothing to see.  Do you have any server logs that might show what happened when the action was running?

**Comment by joyozhang** [comment]
@kesmit13 , Could you please let me know which log I should take? 
The error seems to happen when use the large epoch to training (some case that taking a long time to train).

**Comment by sasxianhu** [comment]
The CAS server log.

**Comment by ethem-kinginthenorth** [comment]
@joyozhang @kesmit13 wondering if there is any update on this issue?

**Comment by joyozhang** [comment]
I made some changes to my code to use gpu, and the error was disappeared.
For now I can't reproduce the error. I'll let you know if same error happens again.

**Comment by ethem-kinginthenorth** [comment]
thanks. I am closing the issue for now and please feel free to re-open this or a new one when you have further issues. thanks
