### ISSUE TITLE
Error after updated to v1.1.0

### ISSUE THREAD

**Issue by joyozhang** [sassoftware/python-dlpy#170]
model = Model.from_onnx_model(sess, 
                               onnx_model=onnx_model,
                               output_model_table='tiny_yolov2',
                               scale=1/255.,
                               output_layer=output_layer)
--------------------------------------------------------------
---------------------------------------------------------------------------
OnnxParseError                            Traceback (most recent call last)
<ipython-input-12-27772199a8c1> in <module>
      3                                output_model_table='tiny_yolov2',
      4                                scale=1/255.,
----> 5                                output_layer=output_layer)

/opt/sas/python/lib/python3.7/site-packages/dlpy/network.py in from_onnx_model(cls, conn, onnx_model, output_model_table, offsets, scale, std, output_layer)
    557         model_name = model_table_opts['name']
    558 
--> 559         _layers = onnx_to_sas(onnx_model, model_name, output_layer)
    560         if offsets is not None:
    561             _layers[0].config.update(offsets = offsets)

/opt/sas/python/lib/python3.7/site-packages/dlpy/model_conversion/sas_onnx_parse.py in onnx_to_sas(model, model_name, output_layer)
    100     for n in model.graph.node:
    101         if n.op_type not in _onnx_ops + list(_act_map.keys()):
--> 102             raise OnnxParseError('Unsupported op: ' + n.op_type)
    103 
    104     # get shapes of tensors in graph

OnnxParseError: Unsupported op: ImageScaler

**Comment by ethem-kinginthenorth** [comment]
This is due to a change in onnx. I believe we made this change to cover that change. can you check your onnx version?

**Comment by joyozhang** [comment]
the onnx version is 1.5.0
---------------------------------------------------------------
onnx in /opt/sas/python/lib/python3.7/site-packages (1.5.0)

**Comment by ethem-kinginthenorth** [comment]
@yg2288 could you please take a look at this issue?

**Comment by yg2288** [comment]
I will update the onnx models which should resolve this - it has some ops that are deprecated in the latest version.  Btw, if you re-export the onnx model using the latest version of dlpy, it should work since we removed ImageScaler recently.

**Comment by joyozhang** [comment]
@yg2288 Thanks.

**Comment by ethem-kinginthenorth** [comment]
@joyozhang have you tried what @yg2288 suggests 're-export the onnx model using the latest version of dlpy'? thanks

**Comment by ethem-kinginthenorth** [comment]
@joyozhang wondering if there is any update on this?

**Comment by joyozhang** [comment]
Thanks guys, That works for me.

**Comment by ethem-kinginthenorth** [comment]
Closing the issue. Please feel free to open a new one if you have further questions. thanks

**Comment by banbsyip** [comment]
@yg2288 ，where can I download the updated onnx models?

**Comment by banbsyip** [comment]
> @yg2288 ，where can I download the updated onnx models?
I have find it in
http://support.sas.com/documentation/prod-p/vdmml/zip/index.html
