### ISSUE TITLE
ResNet50_Caffe API load with error: Parameter 'gpuModel' is not recognized.

### ISSUE THREAD

**Issue by danielecazzari** [sassoftware/python-dlpy#171]
After updating to version 1.1.0 if I try to load the RestNet50 with this command:

model_R50 = ResNet50_Caffe(s, n_channels=3, random_flip='HV', 
                       pre_trained_weights_file=modelPath+'ResNet-50-model.caffemodel.h5',
                       pre_trained_weights=True,
                       offsets=tr_img.channel_means,
                       include_top=False, n_classes=2, random_crop='none')

I receive the following output and errors:

NOTE: no dataspec(s) provided - creating image classification model.
NOTE: Model weights attached successfully!
NOTE: Model table is attached successfully!
NOTE: Model is named to "resnet50_caffe" according to the model name in the table.
ERROR: Parameter 'gpuModel' is not recognized.
ERROR: Expecting one of the following: nThreads, modelTable, modelWeights, labelTable, formatType, weightFilePath, weightFileCaslib, model, casout, path, caslib.
ERROR: The action stopped due to errors.
ERROR: The file or path 'resnet50_caffe_weights' is not available in the file system.
ERROR: Table 'resnet50_caffe_weights' could not be loaded.
ERROR: Failure opening table 'resnet50_caffe_weights': A table could not be loaded.
ERROR: The action stopped due to errors.

Same results with the version downloaded from git.

**Comment by ethem-kinginthenorth** [comment]
@eusdougc would you please take a look at this. thanks

**Comment by eusdougc** [comment]
@danielecazzari - what version of Viya are you using?  The parameter _gpuModel_ was introduced in the most recent version of Viya.

**Comment by danielecazzari** [comment]
I'm using the latest shipment viya 3.4 and vdmml 8.4

**Comment by eusdougc** [comment]
Just to be clear, you have the version of Viya released late May/early June of this year?  I ask because I believe the Viya version number has not changed for the last two releases.  The error you are seeing would occur if you are not running the Viya version released about a month ago.

**Comment by danielecazzari** [comment]
I update the license to shipment event 19w21 and I did last repository update + yum update on beginning of June. To get latest version you mention should I perform an additional yum update or request a new license for another shipment event?

**Comment by eusdougc** [comment]
That should be the correct code base.  I will see if I can reproduce the error you are seeing.

**Comment by eusdougc** [comment]
I can reproduce the problem and I have a fix for this issue.  We will have to do some testing and validation before we release it.  I will let you know when you can clone the repo to pick up the fix.

**Comment by ethem-kinginthenorth** [comment]
@danielecazzari : thanks to @eusdougc , a fix has been pushed for this issue. Please do clone a local copy of dlpy and add that local location to your pythonpath. This would resolve the issue. Please let us know if there is any issues. thanks

**Comment by danielecazzari** [comment]
Thanks @ethem-kinginthenorth and @eusdougc, the fix is currently working and I was able to successfully train the model.

I'm closing the issue.
