### ISSUE TITLE
Where can I get pre-trained model of Faster-rcnn?

### ISSUE THREAD

**Issue by MasayukiNishii** [sassoftware/python-dlpy#173]
In the example code below about object detection of faster-rcnn, I want to follow up the operation.
https://github.com/sassoftware/python-dlpy/blob/master/examples/object_detection/FasterRCNN_Example.ipynb

Would you tell me from where can I download the pre-trained information like below to build and run faster-rcnn?
'rcnn_trainSetJoined_Yolo_496_fromRSZ.sashdat'
'VGG16_RCNN_Weights_YOLOWithLabelAttr1'

**Comment by ethem-kinginthenorth** [comment]
It is quite large therefore, we haven't shared it. Let me check a couple of folks to see what is the best way to share such large files.

**Comment by MasayukiNishii** [comment]
Thank you for informing path to relating materials.
