### ISSUE TITLE
Error loading an RNN model

### ISSUE THREAD

**Issue by xiaozhuoc** [sassoftware/python-dlpy#174]
model = Model(s)
model.load("/cas/DeepLearn/dlpy/test/datasources/sample_acoustic_model.sashdat")

It tells me that:
NOTE: Model table is loaded successfully!
NOTE: Model is renamed to "asr" according to the model name in the table.
Traceback (most recent call last):
  File "U:/projects/python-dlpy/dlpy/speech.py", line 434, in <module>
    model.load("/cas/DeepLearn/dlpy/test/datasources/sample_acoustic_model.sashdat")
  File "U:\projects\python-dlpy\dlpy\network.py", line 721, in load
    model.layers.append(extract_recurrent_layer(layer_table = layer_table))                
NameError: name 'model' is not defined

The same code work with the example file "vgg16.sashdat".

**Comment by ethem-kinginthenorth** [comment]
@xiaozhuoc  I believe I fixed this recently. Do you mind doing a git clone and add that to your pythonpath to get the latest changes? Thanks

**Comment by ethem-kinginthenorth** [comment]
@xiaozhuoc any chance have you tried the work around?

**Comment by xiaozhuoc** [comment]
Clone the latest version and it works now.
