### ISSUE TITLE
Speech Recognition - Audio Training Dataset

### ISSUE THREAD

**Issue by 9to5routine** [sassoftware/python-dlpy#177]
Hi, is it possible to share the dataset used in AudioTraining.ipynb? I've been trying to replicate the example using my own small audio dataset but have been unsuccessful so far.

![image](https://user-images.githubusercontent.com/40623224/62192120-99a2bb80-b3a7-11e9-9b14-cbd82bd92c6c.png)

The code above shows a snapshot from the AudioTraining.ipynb example. From the example, seems like both the listingFile and groundtruth file is supposed to be stored on the server end, but the AudioTable.create_audio_table() function looks for the groundtruth file on the client side instead.

**Comment by ethem-kinginthenorth** [comment]
it is here: https://github.com/sassoftware/python-dlpy/tree/master/dlpy/tests/datasources

I think there is a confusion - we might need a better paths, let me explain:
 the ground truth has to be in the client as we are doing some pre-processing on that file and then sending it to the server. If your client and the server are the same os and have similar access to folders, this works just fine. As we anonymize the locations and such, we have missed this point. Thanks for pointing out. I will pass a different path for the ground truth file. thanks again.
