### ISSUE TITLE
Speech Recognition - Audio Training Issue

### ISSUE THREAD

**Issue by 9to5routine** [sassoftware/python-dlpy#179]
Hi, I am trying to replicate the AudioTraining.ipynb example on my end, with windows as my client side OS and linux as my server side OS.

Extracting my audio features ran successfully, as shown below. The path to my first audio file was recorded as "/home/sasdemo/STT1/84-121123-0000.wav"

![image](https://user-images.githubusercontent.com/40623224/62282564-59643b80-b482-11e9-9f70-475d85cdb6fd.png)

However, I ran into issues when loading the Audio metadata. As the groundtruth file is stored on the client side (windows) and the audio files are stored on the server side (linux), the paths i specified for creating the audio metadata resembles the following:

me = AudioTable.load_audio_metadata(conn, "C:/Users/cwh/Desktop/Speech Recognition Dataset 1/groundtruth.txt", "/home/sasdemo/STT1")

The table containing the audio metadata is created as follows:

![image](https://user-images.githubusercontent.com/40623224/62282994-29696800-b483-11e9-868e-b1912c7edb19.png)

The _path_ variable was generated, appending a "\" and the filename to the directory specified in the load_audio_metadata function. The path to my first audio file here was recorded as "/home/sasdemo/STT1\84-121123-0000.wav". Note the last backward slash in this path.

Due to the incorrect backward slash appended to the path, I am unable to use the _path_ variable as a common ID to join the tables together.

Any help would be greatly appreciated!

**Comment by ethem-kinginthenorth** [comment]
When we have this case, we try to get file two separators: 1) for os of the client and 2) for os of the server. It seems like in this case, we used the client fs in the server side. I will look into this issue. Maybe joining with filenames would be a better idea than the full path. Thanks for pointing out. I will keep this issue updated.

**Comment by ethem-kinginthenorth** [comment]
I did some changes with a recent push and updated the example. If you do a git-clone and use the most recent version, you should be able to have a fixed dlpy for your issue. thanks

**Comment by ethem-kinginthenorth** [comment]
@9to5routine I am wondering if you had any time to check the fix? thanks

**Comment by 9to5routine** [comment]
Yes, the file separator issue has been resolved; thanks so much for the help!
