### ISSUE TITLE
No Error When Using Wrong Platform Path For AudioTable.load_audio_files()

### ISSUE THREAD

**Issue by DevPhelps** [sassoftware/python-dlpy#181]
Good afternoon.

If you attempt to call AudioTable.load_audio_files() with a Windows path, but have the server be Linux based (or vice versa), you get no feedback whatsoever.  This is because the logic is checking for forward slashes on Linux and backward slashes on Windows and if it doesn’t split on these, the function [returns None](https://github.com/sassoftware/python-dlpy/blob/master/dlpy/audio.py#L97).

A message that covers this situation would be very helpful.  Thank you!

**Comment by ethem-kinginthenorth** [comment]
I am adding a message. the current design assumes that the path is accessible by the CAS server. Adding a warning message.
