### ISSUE TITLE
How can I build an anto-encoder for image?

### ISSUE THREAD

**Issue by chungdz** [sassoftware/python-dlpy#184]
Dear all,
We now use keras to build an auto-encoder with code:
```
input_img = Input(shape=(28, 28, 3))
x = Convolution2D(16, (3, 3), activation='relu', padding='same')(input_img) 
x = MaxPooling2D((2, 2), padding='same')(x)    
x = Convolution2D(8, (3, 3), activation='relu', padding='same')(x)    
x = MaxPooling2D((2, 2), padding='same')(x)    
x = Convolution2D(8, (3, 3), activation='relu', padding='same')(x)    
encoded = MaxPooling2D((2, 2), padding='same', name='encoded')(x)
x = Convolution2D(8, (3, 3), activation='relu', padding='same')(encoded)    
x = UpSampling2D((2, 2))(x)    
x = Convolution2D(8, (3, 3), activation='relu', padding='same')(x)    
x = UpSampling2D((2, 2))(x)    
x = Convolution2D(16, (3, 3), activation='relu')(x)    
x = UpSampling2D((2, 2))(x)    
decoded = Convolution2D(3, (3, 3), activation='sigmoid', padding='same', name='decoded')(x)
autoencoder = Model(inputs=input_img, outputs=decoded)
```

We want to use the layer "encoded" to encode the image as a vector for next analysis. 
Is there any way to build a model like this in dlpy?
Thank you

**Comment by sasxianhu** [comment]
Yes, check UNet in https://github.com/sassoftware/python-dlpy/blob/master/dlpy/applications.py.
Use Conv2DTranspose for upsampling.
Use data layer in dataSpecs to specify the output segmentation layer same as the input layer.
use layer_out to extract the features when you finish training.

**Comment by ethem-kinginthenorth** [comment]
@chungdz feel free to share your auto-encoder with us, I would be very happy put that in the examples. thanks

**Comment by chungdz** [comment]
I met a confusing problem when trying to build the auto_encoder:
```
data_input = Input(n_channels=3, width=28, height=28, scale=1)
conv_1 = Conv2d(n_filters=16, width=3, height=3, stride=1, padding=1, act='elu')(data_input)
pool_1 = Pooling(width=2, height=2, stride=2, padding=0, pool='max')(conv_1)
conv_2 = Conv2d(n_filters=8, width=3, height=3, stride=1, padding=1, act='elu')(pool_1)
pool_1 = Pooling(width=2, height=2, stride=2, padding=0, pool='max')(conv_2)
conv_3 = Conv2d(n_filters=8, width=3, height=3, stride=1, padding=1, act='elu')(pool_1)
encoder = Pooling(width=2, height=2, stride=2, padding=1, pool='max', name='encoder')(conv_3)

conv_4 = Conv2d(n_filters=8, width=3, height=3, stride=1, padding=1, act='elu')(encoder)
upsample_1 = Conv2DTranspose(n_filters=8, width=2, height=2, output_size=(8, 8, 8))(conv_4)
conv_5 = Conv2d(n_filters=8, width=3, height=3, stride=1, padding=1, act='elu')(upsample_1)
upsample_2 = Conv2DTranspose(n_filters=8, width=2, height=2, output_size=(8, 16, 16))(conv_5)
conv_6 = Conv2d(n_filters=16, width=3, height=3, stride=1, padding=0, act='elu')(upsample_2)
upsample_3 = Conv2DTranspose(n_filters=16, width=2, height=2, output_size=(16, 28, 28))(conv_6)
decoder = Conv2d(n_filters=3, width=3, height=3, stride=1, padding=1, act='elu')(upsample_3)

seg1 = Segmentation(name='Segmentation1')(decoder)
model = Model(conn, inputs=data_input, outputs=seg1, model_table='auto_encoder')
model.compile()
```
The response is like:
![image](https://user-images.githubusercontent.com/24776624/62751230-807bc800-ba95-11e9-9f46-3feb83ed1f9d.png)

And there's a similar problem when I tried to build the UNet in the dlpy.applications:
`unet = UNet(conn)`

![image](https://user-images.githubusercontent.com/24776624/62751351-f8e28900-ba95-11e9-9d15-7bffedf0006e.png)

When I added a segmentation layer directly, I also got this problem:
![image](https://user-images.githubusercontent.com/24776624/62751791-97231e80-ba97-11e9-8db1-f39432884313.png)


It seems like there are something in my environment haven't been set to support the Conv2DTranspose layer and Segmentation layer yet. I've checked my packages, and found that the version of swat is 1.5.1 and dlpy is 1.1.1.
Could you please give some advice to solve this?

**Comment by sasxianhu** [comment]
You have to have VDMML 8.4.

**Comment by chungdz** [comment]
I now successfully build an auto-encoder like this:

```
data_input = Input(n_channels=3, width=28, height=28, scale=1)
conv_1 = Conv2d(n_filters=16, width=3, height=3, stride=1, padding=1, act='elu')(data_input)
pool_1 = Pooling(width=2, height=2, stride=2, padding=0, pool='max')(conv_1)
conv_2 = Conv2d(n_filters=8, width=3, height=3, stride=1, padding=1, act='elu')(pool_1)
pool_1 = Pooling(width=2, height=2, stride=2, padding=0, pool='max')(conv_2)
conv_3 = Conv2d(n_filters=8, width=3, height=3, stride=1, padding=1, act='elu')(pool_1)
encoder = Pooling(width=2, height=2, stride=2, padding=1, pool='max', name='encoder')(conv_3)

conv_4 = Conv2d(n_filters=8, width=3, height=3, stride=1, padding=1, act='elu')(encoder)
upsample_1 = Conv2DTranspose(8, 3, output_size=(8, 8, 8), padding=1, stride=2, act='relu')(conv_4)
conv_5 = Conv2d(n_filters=8, width=3, height=3, stride=1, padding=1, act='elu')(upsample_1)
upsample_2 = Conv2DTranspose(8, 4, padding=1, stride=2, act='relu')(conv_5)
conv_6 = Conv2d(n_filters=16, width=3, height=3, stride=1, padding=0, act='elu')(upsample_2)
upsample_3 = Conv2DTranspose(16, 4, padding=1, stride=2, act='relu')(conv_6)
decoder = Conv2d(n_filters=3, width=3, height=3, stride=1, padding=1, act='elu')(upsample_3)

seg1 = Segmentation(name='Segmentation1')(decoder)
model = Model(conn, inputs=data_input, outputs=seg1, model_table='auto_encoder')
model.compile()
```

but when I try to fit the model using the code 

```
image_data = ImageTable.load_files(conn=conn, path=mypath)
image_data = image_data.resize(width=28, height=28, inplace=False)

optimization=Optimizer(mini_batch_size = 64, reg_l2=0.001,
                    algorithm=dict(method = 'momentum',  
                                   momentum = 0.9,
                                   clipgradmin = -1000,    
                                   clipgradmax = 1000,
                                   learningRatePolicy = 'MULTISTEP',  
                                   gamma = 0.2,   
                                   steps = [35, 70],
                                   learningRate = 0.001),    
                    max_epochs=1, log_level=2
                   )
r = model.fit(data = image_data, inputs='_image_', target='_image_',
                n_threads = 1,  
                optimizer=optimization)
```
I got this error message:
> DataSpecs must be used to specify values for all of the supported layers if the model contains segmentation, detection, closs or multi-task layers. If you use dataSpecs to specify values for any supported layer, you must use dataSpecs to specify values for all of the supported layers.

I don't know how to specify DataSpecs, and I have not found any example. Please help.

**Comment by ethem-kinginthenorth** [comment]
@chungdz please look at the examples:
- https://github.com/sassoftware/python-dlpy/blob/master/examples/object_detection/FasterRCNN_Example.ipynb [cell 31]
- https://github.com/sassoftware/python-dlpy/blob/master/examples/object_detection/SimpleObjectDetection.ipynb [cell11]
- https://github.com/sassoftware/python-dlpy/blob/master/examples/segmentation/semantic_segmentation.ipynb [cell13]

 hope this helps. thanks

**Comment by chungdz** [comment]
As the auto-encoder has the same input and output, I originally set the DataSpec like this

```
image_data = ImageTable.load_files(conn=conn, path=mypath)
image_data = image_data.resize(width=28, height=28, inplace=False)

targets = ['_image_']
inputVars = ['_image_']

data_specs = [DataSpec(type_='IMAGE', layer='Input1', data=inputVars),
              DataSpec(type_='IMAGE', layer='Segmentation1', data=targets)]
```
When I tried to fit the model, I got this message:

> Only one dataSpecs declaration allowed per variable

So I tried to copy the column '\_image\_' in the table. As I didn't find direct methods to copy columns, I thought I could firstly copy the table and then merge two tables, to get two same columns.

```
image_data_cp = image_data.copy(deep=True)
trainTbl = image_data.merge(image_data_cp, how='inner', on='_id_', 
suffixes=('input', 'output'),  casout=dict(name='train_set'))
```

And I got this error message:

> ERROR: Syntax error, expecting one of the following: a name, a numeric constant, $, -, :, VARCHAR, _ALL_, _CHARACTER_, _CHAR_, _NUMERIC_.
> ERROR: Syntax error, statement will be ignored.
> ERROR: DATA step in Cloud Analytic Services does not support varbinary or binary variables.
> ERROR: Invalid DROP, KEEP, or RENAME option on file 
> ERROR: Invalid DROP, KEEP, or RENAME option on file 
> ERROR: Syntax error, expecting one of the following: a name, a numeric constant, $, -, :, VARCHAR, _ALL_, _CHARACTER_, _CHAR_, _NUMERIC_.  (occurred 40 times)
> ERROR: Syntax error, statement will be ignored.  (occurred 40 times)
> ERROR: DATA step in Cloud Analytic Services does not support varbinary or binary variables.  (occurred 2 times)
> ERROR: The action stopped due to errors.
> ---------------------------------------------------------------------------
> SWATError                                 Traceback (most recent call last)
> <ipython-input-193-df8cdd0ac56e> in <module>()
>       1 trainTbl = image_data.merge(image_data_cp, how='inner', on='_id_', suffixes=('input', 'output'), 
> ----> 2                              casout=dict(name='train_set'))
>       3 trainTbl.columns
> 
> /opt/data/share/anaconda3/lib/python3.6/site-packages/swat/cas/table.py in merge(self, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, casout)
>    6472                      right_on=right_on, left_index=left_index,
>    6473                      right_index=right_index, sort=sort, suffixes=suffixes,
> -> 6474                      copy=copy, indicator=indicator, casout=casout)
>    6475 
>    6476 #   def join(self, other, on=None, how='left', lsuffix='', rsuffix='', sort=False):
> 
> /opt/data/share/anaconda3/lib/python3.6/site-packages/swat/cas/table.py in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate, casout)
>     533                                              _apptag='UI', _messagelevel='error')
>     534         if out.status:
> --> 535             raise SWATError(out.status)
>     536 
>     537     finally:
> 
> SWATError: Action stopped due to client interrupt request.

I have checked the example mentioned above, they all use the sas7hdat file to build tables. Which means the training set is already prepared before. I know that I can first use sas code to convert the image table I want, but I want to integrate all the process in python. 

Could you please help me about this?

**Comment by ethem-kinginthenorth** [comment]
![step1](https://user-images.githubusercontent.com/44275619/62944992-d5785080-bdab-11e9-8c0a-55ac3fa7a246.png)

**Comment by ethem-kinginthenorth** [comment]
![step2](https://user-images.githubusercontent.com/44275619/62945000-da3d0480-bdab-11e9-847a-b06cca5392a6.png)

**Comment by ethem-kinginthenorth** [comment]
hope these steps help. thanks

**Comment by chungdz** [comment]
I have refered to answers and example of UNet and wrote the code. And I met the problem when trying to fit the model:
![image](https://user-images.githubusercontent.com/24776624/62993479-0333c700-be8a-11e9-8faf-c7ff226e2d26.png)

I wondered if it was because the pixel values in my picture was diverse, but the segmentation layer only expected limited pixel values, which it told me could not exceed the filters of the source layer of the segmentation layer.

So, I have tried to set the last convolution layer to have 310 filters, and the model started training. Are there other approaches to let the model output the original picture, while keeping the number of the filters the same as the channels of the picture, namely 3?  

And when I checked the output of the model segmentation layer, I found that the output had 28\*28\*1 dimensions, which means the model output had only one channel. Was I wrong about something? I expected the model to output 28\*28\*3 dimensions. Here's the code I used to do the prediction.
![image](https://user-images.githubusercontent.com/24776624/63004965-2a03f480-beae-11e9-95b5-c8a312c97d23.png)
![image](https://user-images.githubusercontent.com/24776624/63005563-62f09900-beaf-11e9-90f3-6ef7e86f4dea.png)
![image](https://user-images.githubusercontent.com/24776624/63005588-6c7a0100-beaf-11e9-9295-0c6637a83525.png)


Here are the pictures I used both in input layer and segmentation layer: 
![image](https://user-images.githubusercontent.com/24776624/62997668-a0e3c200-be9b-11e9-8ef8-165b832ede7f.png)

The table I built for model was this:
```
image_data = ImageTable.load_files(conn=conn, path='/opt/data/share/data/jupyter/HYF/img', casout=dict(name='data_input'))
image_data = image_data.resize(width=28, height=28, inplace=False)

conn.table.partition(table=image_data, casout=dict(name='image_data_cp', replace=True))
image_data_cp = conn.CASTable('image_data_cp')
conn.table.altertable(columns=[{'rename':'_image_copy_', 'name':'_image_'}], name=image_data_cp)

conn.deeplearn.dljoin(annotatedtable=image_data, table=image_data_cp, 
                      casout=dict(name='merged_table', replace=True), id='_filename_0')
merged_table = conn.CASTable('merged_table')
merged_table.columninfo()
```
![image](https://user-images.githubusercontent.com/24776624/62992711-0a0d0a80-be87-11e9-8ab6-110f0d5411ad.png)

The model structure I firstly used was this, and I have to change the number of the filters in the last convolution layer to 310, in order to begin the training process:
```
data_input = Input(n_channels=3, width=28, height=28, scale=1, name='Input')
conv_1 = Conv2d(n_filters=16, width=3, height=3, stride=1, padding=1, act='elu')(data_input)
pool_1 = Pooling(width=2, height=2, stride=2, padding=0, pool='max')(conv_1)
conv_2 = Conv2d(n_filters=8, width=3, height=3, stride=1, padding=1, act='elu')(pool_1)
pool_1 = Pooling(width=2, height=2, stride=2, padding=0, pool='max')(conv_2)
conv_3 = Conv2d(n_filters=8, width=3, height=3, stride=1, padding=1, act='elu')(pool_1)
encoder = Pooling(width=2, height=2, stride=2, padding=1, pool='max', name='encoder')(conv_3)

conv_4 = Conv2d(n_filters=8, width=3, height=3, stride=1, padding=1, act='elu')(encoder)
upsample_1 = Conv2DTranspose(8, 3, padding=1, stride=2, output_padding=1, act='relu')(conv_4)
conv_5 = Conv2d(n_filters=8, width=3, height=3, stride=1, padding=1, act='elu')(upsample_1)
upsample_2 = Conv2DTranspose(8, 4, padding=1, stride=2, act='relu')(conv_5)
conv_6 = Conv2d(n_filters=16, width=3, height=3, stride=1, padding=0, act='elu')(upsample_2)
upsample_3 = Conv2DTranspose(16, 4, padding=1, stride=2, act='relu')(conv_6)
decoder = Conv2d(n_filters=3, width=3, height=3, stride=1, padding=1, act='logistic', name='decoder')(upsample_3)

seg1 = Segmentation(name='Segmentation_1')(decoder)
model = Model(conn, inputs=data_input, outputs=seg1, model_table='auto_encoder')
model.compile()
model.summary

```
![image](https://user-images.githubusercontent.com/24776624/62992626-b995ad00-be86-11e9-8099-88f5483f9d24.png)

**Comment by dxq77dxq** [comment]
If I understand it correctly, you're trying to build an image auto-encoder model to encode the image as a vector. In this case, we use dataLayer in dataSpecs as below:

```
data_specs = [DataSpec(type_='IMAGE', layer='Input1', data=inputVars),
                       DataSpec(type_='IMAGE', layer='Segmentation1', dataLayer='Input1')]
```

In this way, we're specifying that the Segmentation1 layer uses the same same as in Input1. Hope this solves your problem and please let us know if you have further questions.

**Comment by chungdz** [comment]
I completed the auto_encoder code and upload it in my github repositories:

https://github.com/chungdz/img/blob/master/auto_encoder.ipynb

Was I right about the approach to do the comparison between input and output?  When I checked the image, I found they were almost the same. So I doubted whether I fetched a right table.

![image](https://user-images.githubusercontent.com/24776624/63077544-39954300-bf6b-11e9-8cd1-2e65d8287252.png)


I fetched the prediction output using the code: 
```
model.predict(image_data)
result = conn.CASTable(model.valid_res_tbl.name)
```
And converted it into ImageTable:

```
result = ImageTable.from_table(result)
conn.table.altertable(columns=[{'rename':'_image_output_', 'name':'_image_'}], name=result)

```

Then  I merged the input table and output table for comparison

```
conn.deeplearn.dljoin(annotatedtable=image_data, table=result, 
                      casout=dict(name='merged_table', replace=True), id='_filename_0')
merged_table = conn.CASTable('merged_table')
```

**Comment by dxq77dxq** [comment]
The comparison looks reasonable to me, as the resulting fit error is small enough. I would also suggest using the following code to get image summaries for both _image_ and _image_output_.
`
conn.summarizeImages('merged_table', image = '_image_')
conn.summarizeImages('merged_table', image = '_image_output_')
`

**Comment by chungdz** [comment]
I complete the auto-encoder code, and share it in my repository. @ethem-kinginthenorth you have mentioned before that you might put it as an example :
https://github.com/chungdz/img/blob/master/auto_encoder.ipynb

I believe it's time to close this issue?

**Comment by ethem-kinginthenorth** [comment]
could you please do a pull-request to the master branch, I will review it and then merge it. Thanks for your help. I am closing the issue.
