### ISSUE TITLE
word_embedding file in Image captioning

### ISSUE THREAD

**Issue by pynyah** [sassoftware/python-dlpy#187]
Hi,
where can I find word_embedding.txt file in this repository?

Thanks

**Comment by ice-sas** [comment]
Hi,
Any pre-trained word embedding would be fine. The one we used is a tab delimited embedding where the first column had the terms and the rest of the columns had word embeddings for those terms. Every row represents a single term.

**Comment by ethem-kinginthenorth** [comment]
I am closing the issue. Please do re-open it if you have any questions.
