### ISSUE TITLE
Issues with Image captioning

### ISSUE THREAD

**Issue by pynyah** [sassoftware/python-dlpy#188]
Hi,

I am getting the errors while generating the embeddings from object detection. Could you please suggest how it can be solved?

![imagecap1](https://user-images.githubusercontent.com/54321951/63406538-dd696d80-c407-11e9-9d66-c042c2e07b17.PNG)
![imagecap2](https://user-images.githubusercontent.com/54321951/63406547-e1958b00-c407-11e9-810d-5dc9f81290d6.PNG)

**Comment by sasxianhu** [comment]
model_path = 'full_size_yolo_313_cls/multi_size_43ep/YOLOV2_MULTISIZE.sashdat'
detection_model = Model(conn)
detection_model.load(model_path)
NOTE: Model table is loaded successfully!
NOTE: Model is renamed to "yolov2_multisize" according to the model name in the table.
**NOTE: YOLOV2_MULTISIZE_weights.sashdat is used as model weigths.**
NOTE: Model weights attached successfully!
NOTE: YOLOV2_MULTISIZE_weights_attr.sashdat is used as weigths attribute.
NOTE: Model attributes attached successfully!

Did you download the model weights?

http://support.sas.com/documentation/prod-p/vdmml/zip/index.html

**Comment by pynyah** [comment]
Thanks for that. 

Which pretrained weight am I supposed to use here
![pic3](https://user-images.githubusercontent.com/54321951/63509893-e5560a00-c4fa-11e9-9b6c-d1fc3352ae39.PNG)

**Comment by sasxianhu** [comment]
http://support.sas.com/documentation/prod-p/vdmml/zip/yolov2_multisize_313cls.zip

download this and put YOLOV2_MULTISIZE_weights.sashdat under the same directory as YOLOV2_MULTISIZE.sashdat.

**Comment by ethem-kinginthenorth** [comment]
@pynyah did you try the link that @sasxianhu suggested?

**Comment by kybowm** [comment]
The link submitted by @sasxianhu is for the YOLO model weights, but I believe @pynyah's code snippet refers to weights for the RNN model.

To my knowledge, if you want to use pretrained weights for the RNN model, you must supply them yourself. You should, however, still be able to train the model from scratch starting in the "Train the model section"

**Comment by ethem-kinginthenorth** [comment]
I am closing the issue. Please do re-open the issue, if you have any questions. thanks.
