### ISSUE TITLE
Model weights for Image Captioning example

### ISSUE THREAD

**Issue by Kaynelua** [sassoftware/python-dlpy#189]
Hi, may i ask for a link to download the h5 file for VGG_16 model used in the Image Captioning example? I tried googling and only managed to get the binaryproto format file downloaded  from : http://www.robots.ox.ac.uk/~vgg/software/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel

Due to difference in format, loading of weights failed and i got the following error message : 

NOTE: Model table is attached successfully!
NOTE: Model is named to "vgg16" according to the model name in the table.
NOTE: Cloud Analytic Services made the uploaded file available as table NEW_LABEL_TABLE_YGJJWN in caslib CASUSER(viyademo01).
NOTE: The table NEW_LABEL_TABLE_YGJJWN has been created in caslib CASUSER(viyademo01) from binary data uploaded to Cloud Analytic Services.
NOTE: no dataspec(s) provided - creating image classification model.
NOTE: Model weights attached successfully!
ERROR: The Caffe model file not found.
ERROR: The action stopped due to errors.

**Comment by sasxianhu** [comment]
http://support.sas.com/documentation/prod-p/vdmml/zip/index.html
