### ISSUE TITLE
Issue with vectorizing detected objects using embeddings file

### ISSUE THREAD

**Issue by Kaynelua** [sassoftware/python-dlpy#192]
Hi there,

I am having some issues with visuzalizing the vectorized detected objects. Running detected_objects.head() gives me a table looking like this :

![image](https://user-images.githubusercontent.com/26089562/63490239-ca799a80-c4e6-11e9-8ab3-69cd222deb3c.png)

The embeddings file i am using was downloaded from : http://nlp.stanford.edu/data/glove.6B.zip
I am using the 200dimension one but am unable to see the values within the columns as per the example.

**Comment by Kaynelua** [comment]
Realised that this may be due to the fact that the embeddings file downloaded isnt tab delimited and trying to visualize the WORD_EMBEDDINGS cas table gives a table looking like this :

![image](https://user-images.githubusercontent.com/26089562/63494993-8770f480-c4f1-11e9-94bd-50b86d35fae1.png)

which i am guessing isnt correct.

Perhaps you could provide a link to a tab delimited word_embedding file used in this example.
Thank you

**Comment by pynyah** [comment]
> Realised that this may be due to the fact that the embeddings file downloaded isnt tab delimited and trying to visualize the WORD_EMBEDDINGS cas table gives a table looking like this :
> 
> ![image](https://user-images.githubusercontent.com/26089562/63494993-8770f480-c4f1-11e9-94bd-50b86d35fae1.png)
> 
> which i am guessing isnt correct.
> 
> Perhaps you could provide a link to a tab delimited word_embedding file used in this example.
> Thank you

Hi, 

Were you able to fix this? if yes, then please share how. I am experiencing the same issue. Thanks in advance.

**Comment by sasxianhu** [comment]
Close this one.
One example is below. 

https://go.documentation.sas.com/?docsetId=casdlpg&docsetTarget=n05117l9utesr0n11g9wqwofcz2m.htm&docsetVersion=8.5&locale=en#p0ltjtvcl7tc8ln1uf9zu4yupssw

s.upload('/path/to/glove.txt', casout=dict(name='glove', replace=True),
          importoptions=dict(fileType='delimited', delimiter='\t'))
