### ISSUE TITLE
Create Captioning Table: Object width

### ISSUE THREAD

**Issue by pynyah** [sassoftware/python-dlpy#195]
The function "createcaptioningtable" doesnt take the argument as objectwidth. It throws an error

**Comment by ethem-kinginthenorth** [comment]
@pynyah that is true, if you check the source code, you can see that create_captioning_table does not have a "object_width" argument/input. I am not sure what object_width parameter would be doing in anyways. thanks

**Comment by ethem-kinginthenorth** [comment]
I am closing the issue. Please re-open it, if you have any questions.
