### ISSUE TITLE
Issue with image captioning example

### ISSUE THREAD

**Issue by pynyah** [sassoftware/python-dlpy#196]
I am trying to execute the cell no 31 (as per the example), however I am facing the following issue
![pic4](https://user-images.githubusercontent.com/54321951/63687887-64ad4b80-c823-11e9-80be-8123059f3dc8.PNG)

**Comment by sasxianhu** [comment]
This is the basic CAS question. You cannot access the absolute path under CAS. You have either copy your file to an existing caslib or create a new one that can access the file.

Best,
XQ

On Aug 26, 2019, at 7:33 AM, pynyah <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

I am trying to execute the cell no 31 (as per the example), however I am facing the following issue
[pic4]<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F54321951%2F63687887-64ad4b80-c823-11e9-80be-8123059f3dc8.PNG&data=02%7C01%7Cxiangqian.hu%40sas.com%7C5ed68ab983c94561ced808d72a19347f%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C637024160054296151&sdata=zJbyAvbNg9km8Ea%2BJ0IR3W93jKom5lxJ2brM717PRMA%3D&reserved=0>

**Comment by ethem-kinginthenorth** [comment]
@pynyah loadtable is a CAS action. In dlpy we try our best to give you all the convenient apis that would hide these absolute path relative path things. but in CAS actions you are on your own. please let us know if you need more questions. thanks
