### ISSUE TITLE
Differences between SAS Documentation and DLPy Documentation 

### ISSUE THREAD

**Issue by ngrajales1** [sassoftware/python-dlpy#198]
I was wanting to know which method is recommend to load images using python. SAS documentation states the following:

https://go.documentation.sas.com/?docsetId=casactml&docsetTarget=casactml_loadimages_syntax.htm&docsetVersion=8.2&locale=en

DLPy documentation states the following:

 https://sassoftware.github.io/python-dlpy/generated/dlpy.images.ImageTable.load_files.html#dlpy.images.ImageTable.load_files

The methods are both similar but it seems that the method described in SAS's documentation has further options such as recuse for sub-directories.

**Comment by sasxianhu** [comment]
Depends on your data. If load_files works well (it calls loadImages), just use it. If not, you can switch to loadImages with more options.

**Comment by ngrajales1** [comment]
Okay, thank you for your response. I assume that if I use loadImages then I need to specify a CasLib compared to using load_files which will create a temporary caslib if not specified

**Comment by sasxianhu** [comment]
Yes. DLPy tries its best to hide caslib. If you use the action interfaces, you have to use caslib. :)

**Comment by ethem-kinginthenorth** [comment]
Pretty much. DLPy drives SAS functionalities under the hood. DLPy tries make most of the operations easy while using default parameters with easy access. Also hiding CAS(SAS) specific terminology so that anyone can pick up and start using it.
