### ISSUE TITLE
Problem with sas-dlpy fit method

### ISSUE THREAD

**Issue by vcerrato-pertica** [sassoftware/python-dlpy#200]
Hi,

recently we changed the directory installation of Jupyter, reinstalling Jupyter in another directory (disk space problems) and reinstalling all neccesary packages (I hope so).

The problem has come with the sas-dlpy fit method, other methods works perfectly (and code works on previous installation), but not now.
 
Attached error capture.
![error jupyter](https://user-images.githubusercontent.com/54705927/64008600-b2bd9a00-cb16-11e9-9149-86687618f6ed.png)

FYI, both installations are still in the machine, but only the second one is up. SAS support has told us to delete the old one, but if it is not up, could it generate conflict?

I post this here on the recommendation of Joe Furbee in the SAS communities.

Thanks.

PD: I'm sorry if I have not followed the standard for publishing an issue.

PD2: Sorry for publish an issue on friday ;)

**Comment by sasxianhu** [comment]
freezebatchnormstats is the new option shipped with VDMML 8.4. Can you check the version?

**Comment by vcerrato-pertica** [comment]
This code works on the other Jupyter installation, which is on the same machine and the same software version.

I'm sorry, but I don't know how to check the specific version of that module.

**Comment by sasxianhu** [comment]
Let us check the client package version first .

Can you do these?

swat.__version__
dlpy.__version__

Best,
XQ

On Aug 30, 2019, at 7:32 AM, vcerrato-pertica <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

This code works on the other Jupyter installation, which is on the same machine and the same software version.

I'm sorry, but I don't know how to check the specific version of that module.

**Comment by vcerrato-pertica** [comment]
SWAT Version: 1.5.1
DLPY Version: 1.1.0

**Comment by sasxianhu** [comment]
Do you use the http protocol or binary protocol when connecting to CAS?

Best,
XQ

On Aug 30, 2019, at 8:15 AM, vcerrato-pertica <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

SWAT Version: 1.5.1
DLPY Version: 1.1.0

**Comment by vcerrato-pertica** [comment]
With the SWAT constructor method. I don't know what you mean by binary, but I would be sure it's http because it refers to the machine url and the connection port.

Thanks for your interest.

**Comment by sasxianhu** [comment]
Can you show the line that connects to CAS?

Best,
XQ

On Aug 30, 2019, at 8:24 AM, vcerrato-pertica <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

With the SWAT constructor method. I don't know what you mean by binary, but I would be sure it's http because it refers to the machine url and the connection port.

Thanks for your interest.

**Comment by vcerrato-pertica** [comment]
Sorry for slow to respond, the connection is made like documentation explain: 
`con = swat.CAS(host, port, userid, password)`

**Comment by sasxianhu** [comment]
Do you use VDMML 8.3?

**Comment by vcerrato-pertica** [comment]
cannot check the version, because I don't know how, but I think so

**Comment by sasxianhu** [comment]
Unfortunately, you need use DLPy 1.0.x for VDMML 8.3.

You could use vercon from SAS to check the version if you know how to do it.

**Comment by vcerrato-pertica** [comment]
So why does the same code work if I turn on the other instance of Jupyter by connecting to the same software version?

We will never know...

**Comment by sasxianhu** [comment]
The error basically means the CAS server is 8.3 and does not accept the new options from 8.4. 

It must be something different on your instances.

**Comment by vcerrato-pertica** [comment]
I have to apologize because I have found the difference between the instances. In the sas-dlpy installation we directly use pip install sas-dlpy, without specifying the version. In the first instance, which has a few months, version 1.0.2 was installed, and in this one that was installed a few weeks ago, version 1.1.0 was installed. It has been just two months apart between the versions, but it has been enough to drive us crazy with a code that worked.

Mental note: check the versions.

I apologize again, and thanks for the hints.
