### ISSUE TITLE
Import Tiny Yolo from ONNX with DLPy

### ISSUE THREAD

**Issue by mdziec** [sassoftware/python-dlpy#201]
I wanted to import the model using the example DLPy_Import_ONNX_tinyYoloV2.ipynb, but following the line:
# Update attributes for weights
s.table.attribute (task = 'UPDATE', name = model1.model_weights.name, attrtable = 'yoloweightsAttr')

I get the error:
ERROR: The table tiny_yolov2_weights could not be located in caslib CASUSER (smartparking) of Cloud Analytic Services.
ERROR: The action stopped due to errors.

What could be the reason for this?

**Comment by sasxianhu** [comment]
Did you load the weight like this?
model1.load_weights('/disk/linux/dlpy/tiny_yolov2_weights.onnxmodel.h5')

**Comment by mdziec** [comment]
Thank you very much for your answer. I've already solved the problem.
