### ISSUE TITLE
get_feature_maps needs a better error message when data subset is empty

### ISSUE THREAD

**Issue by mauvesteven** [sassoftware/python-dlpy#21]
When using example1 things work great till I get to:

Model1: View Feature Maps
Feature maps display the output activations for a given filter. The following code uses the test data from the Model1 example to generate and display feature map data. First, create the feature map data. This example uses the test data and filters for images labeled Dolphin. The idx=0 setting indicates that the row 0 index data should be used to construct the feature maps.
In [33]:

model1.get_feature_maps(data=te_img, label='Dolphin', idx=0)
---------------------------------------------------------------------------
DLPyError                                 Traceback (most recent call last)
<ipython-input-33-6535ec0d7695> in <module>
----> 1 model1.get_feature_maps(data=te_img, label='Dolphin', idx=0)

/usr/local/lib/python3.6/site-packages/dlpy/model.py in get_feature_maps(self, data, label, idx, image_id, **kwargs)
   1756         if idx >= uid.shape[0]:
   1757             raise DLPyError('image_id should be an integer between 0'
-> 1758                             ' and {}.'.format(uid.shape[0] - 1))
   1759         uid_value = uid.iloc[idx, 1]
   1760         uid_name = uid.columns[1]

DLPyError: image_id should be an integer between 0 and -1.

when I change label from 'Dolphin' to 'dolphin' it works. I think this function should provide a better error message for this case.

**Comment by yg2288** [comment]
@mauvesteven @ethem-kinginthenorth can this issue be closed?

**Comment by ethem-kinginthenorth** [comment]
@yg2288 let us close this one as you already added a better warning message
