### ISSUE TITLE
DLPy abd SAS VIya 3.3

### ISSUE THREAD

**Issue by ngrajales1** [sassoftware/python-dlpy#211]
I recently observed an issue when trying to use DLPy and Viya 3.3 to read in images using load_files(). 

ERROR: Parameter 'caslib' is not recognized.
ERROR: Expecting one of the following: path, casOut, pathIsList, repeat, quiet, decode, recurse, labelLevels, distribution, addColumns, series, source, outputImages, outputImage, duplicate, silent, decompress.
ERROR: The action stopped due to errors.
ERROR: The file or path 'ImageData_lWIT8D' is not available in the file system.
ERROR: Table 'ImageData_lWIT8D' could not be loaded.
ERROR: Failure opening table 'ImageData_lWIT8D': A table could not be loaded.
ERROR: The action stopped due to errors.

I later realized the issue was related to how load_files will assign a temporary caslib, if one is not stated. Looking at VDDMML 8.2 loadimages does not handle caslibs but VDDMML 8.3 does. So I started to try different versions of DLPy, and I found with some help (thank you @wenyushi ) that the version that worked was V0.7.0. I wanted to bring this issue to light as it is not documented. Now I am not sure if this should be added to documentation for others that are using Viya 3.3, but in case there are others, I wanted to share this.

**Comment by sasxianhu** [comment]
We indeed document this on our home page.

DLPy | SAS Viya | VDMML
-- | -- | --
1.1.x | 3.4 | 8.4
1.0.x | 3.4 | 8.3

**Comment by ngrajales1** [comment]
Okay, Just wanted to throw it out there for any Viya 3.3 users. Thanks for the input.

**Comment by sasxianhu** [comment]
Better update VDMML to the latest one since it has a lot of new features in terms of both traditional ML and DL.

Best,
XQ

On Sep 18, 2019, at 6:01 PM, Nelson Raymond Grajales <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

Okay, Just wanted to throw it out there for any Viya 3.3 users. Thanks for the input.
