### ISSUE TITLE
How to load images organized in folders

### ISSUE THREAD

**Issue by jld23** [sassoftware/python-dlpy#215]
I'm trying to train an computer vision model for the [stanford dog dataset](http://vision.stanford.edu/aditya86/ImageNetDogs/)

When the images are unziped they have a structure like this:
```
ls ./stanford-dogs-dataset/images/Images

n02085620-Chihuahua                       n02096051-Airedale                     n02106030-collie
n02085782-Japanese_spaniel                n02096177-cairn                        n02106166-Border_collie
n02085936-Maltese_dog                     n02096294-Australian_terrier           n02106382-Bouvier_des_Flandres
n02086079-Pekinese       

```
Then within the folders are the images for that breed.
I've tried to follow the examples and the doc but I can't figure out how to use `all_img = ImageTable.load_files(conn, path=dir_path, casout=dict(name='all_img'))` to load the images and use the foldernames as classes.

Is there a better method? I would prefer to not have to reorganzie the data.

**Comment by sasxianhu** [comment]
what is your dir_path? if each folder contains one breed, it should work with something like /stanford-dogs-dataset/images/Images.

**Comment by ethem-kinginthenorth** [comment]
IF you are an experienced SAS user, I should also mention that, this call takes care of the 'caslib' parameter for you under the hood. So you might need to pass the full path.

**Comment by jld23** [comment]
This was user error. The path was from the host not from CAS
