### ISSUE TITLE
Create_Object_detection function only creates .txt files for less than 1/4 of images

### ISSUE THREAD

**Issue by buhrowcr** [sassoftware/python-dlpy#219]
Hello,

My team and I are running into some issues around the .txt file creation when trying to scale out our project, and I was just wondering if you ran into some similar problems. We managed to create the object detection table and get our model to train and work correctly with a small training set of about 100 images. However, obviously the performance is poor because we aren’t training on enough images to meet our customer’s use case. When we moved to a larger training set (about 2,000 images) for some reason the create_object_detection_table function only creates txt files for about 20% of the images. All of our images are the same file type and everyone is labeled at least once. Below is a picture of files in the MobaXterm folder in our image. We are using EEC165_V2_CL. 
![image](https://user-images.githubusercontent.com/54453057/66064690-e6278600-e513-11e9-8cc2-0b804ce4fa01.png)
Thank you for the help!

**Comment by wenyushi** [comment]
How can I access the data or the machine?

**Comment by buhrowcr** [comment]
What is your SAS email? I can send you the RACE image log in email and send you the location of the data in the image.

**Comment by buhrowcr** [comment]
I also don’t know if this helps but my Jupyter Notebook I am working from is under the username: sasdemo, password: Orion123. And it is called I believe NCATS_CVTake2. Hope this helps, thank you!

**Comment by ethem-kinginthenorth** [comment]
I am closing the issue. I believe this is addressed. Please do re-open the issue if you still have issues. thanks
