### ISSUE TITLE
DLPY suport for ppc64le

### ISSUE THREAD

**Issue by ticlazau** [sassoftware/python-dlpy#222]
Hello, 

I will like to know if DLPY is supported on ppc64le - IBM AC922 with NVIDIA V100 GPUs.

Thanks,
FM

**Comment by jld23** [comment]
When I was running on a Power LInux system earlier this week I ran into an error that is fixed in the PR #223. This resolved the issues I ran into.

**Comment by ethem-kinginthenorth** [comment]
@ticlazau I merged the pull request from @jld23 , would you please check if your issue is resolved. thanks

**Comment by ethem-kinginthenorth** [comment]
I am closing the issue assuming that it is resolved. Please do open the issue back if you are still experiencing an issue. thanks
