### ISSUE TITLE
DLPy timeseries Error

### ISSUE THREAD

**Issue by pynyah** [sassoftware/python-dlpy#227]
Hi,

I am facing issues with this step. Although, my datetime format is in order, I am getting the error
![cap9](https://user-images.githubusercontent.com/54321951/66405864-5ea4b000-ea08-11e9-9cf4-0c1a13f34a8e.PNG)
![cap10](https://user-images.githubusercontent.com/54321951/66405882-63696400-ea08-11e9-9484-bff8543accea.PNG)

Appreciate your help

**Comment by sasxianhu** [comment]
Can you try the fetch action?

**Comment by pynyah** [comment]
> Can you try the fetch action?

Here is the result of fetch action. the screenshot just contains time variable (not exposing the entire data)
![cap14](https://user-images.githubusercontent.com/54321951/66413668-72a2de80-ea15-11e9-9ba0-1f702cfc0bb8.PNG)

**Comment by sasxianhu** [comment]
I have to get your data sample to repeat it.

**Comment by pynyah** [comment]
> I have to get your data sample to repeat it.

[data.xlsx](https://github.com/sassoftware/python-dlpy/files/3703630/data.xlsx)

Here is the sample

**Comment by sasxianhu** [comment]
acc_interval : string, optional
            The accumulation interval, such as 'year', 'qtr', 'month', 'week',
            'day', 'hour', 'minute', 'second'.    

Not sure why your 'OBS' means. It works when I tried with hour.

**Comment by sasxianhu** [comment]
You have to use the new user_defined_interval option if your acc_interval is a typical sas date time.

**Comment by ethem-kinginthenorth** [comment]
@pynyah I merged @sasxianhu 's changes. Would you please grab the latest version from the github and try it out to see if that resolves your problem. thanks

**Comment by ethem-kinginthenorth** [comment]
@pynyah, I am closing this issue for now. please let us know if you have any further issues and questions. thanks.
