### ISSUE TITLE
The table tiny_yolov2_weights could not be located in caslib CASUSER(sasdemo) of Cloud Analytic Services.

### ISSUE THREAD

**Issue by banbsyip** [sassoftware/python-dlpy#230]
code:
# first we need to supply some attributes for the dlscore action
# attributes can be converted and saved from an existing SAS model
# s.addcaslib('data1', path='/opt/data/share/data/jupyter/YIP/tiny_yolov2_313cls', activeonadd=False, subdirectories=False)
s.loadtable(path='Tiny-Yolov2_weights.sashdat', caslib='data1', casout=dict(name='Tiny-Yolov2_weights', replace=True))

# Update attributes for weights
print(model1.model_weights.name)
s.table.attribute(task='UPDATE', name=model1.model_weights.name, attrtable='Tiny-Yolov2_weights')

output:
NOTE: Cloud Analytic Services made the file Tiny-Yolov2_weights.sashdat available as table TINY-YOLOV2_WEIGHTS in caslib CASUSER(sasdemo).
tiny_yolov2_weights
ERROR: The table tiny_yolov2_weights could not be located in caslib CASUSER(sasdemo) of Cloud Analytic Services.
ERROR: The action stopped due to errors.
![image](https://user-images.githubusercontent.com/18277076/66620545-79974000-ec13-11e9-812d-82096a54ac43.png)

**Comment by sasxianhu** [comment]
The model_weights.name is tiny_yolov2_weights but your loaded weight table is TINY**-**YOLOV2_WEIGHTS. When you create your model, try to use tiny-yolov2 to match the weight table name.

**Comment by banbsyip** [comment]
> The model_weights.name is tiny_yolov2_weights but your loaded weight table is TINY-YOLOV2_WEIGHTS. When you create your model, try to use tiny-yolov2 to match the weight table name.

thanks for your help, but it is no use for me. whatever I named the table's name, it always named "TINY-YOLOV2_WEIGHTS" as the table's name by the system. 
![image](https://user-images.githubusercontent.com/18277076/66728929-689c3800-ee7a-11e9-9b6e-c30908a32905.png)
![image](https://user-images.githubusercontent.com/18277076/66728944-823d7f80-ee7a-11e9-9117-07094cf427bb.png)
