### ISSUE TITLE
problem of DLPy_Import_ONNX_tinyYoloV2.ipynb

### ISSUE THREAD

**Issue by banbsyip** [sassoftware/python-dlpy#231]
when i run the DLPy_Import_ONNX_tinyYoloV2.ipynb in my local enviroment, i meet two problems.
![image](https://user-images.githubusercontent.com/18277076/66631851-bc6c0e80-ec39-11e9-9f97-2f4e2ccba3b1.png)
![image](https://user-images.githubusercontent.com/18277076/66631709-6b5c1a80-ec39-11e9-9727-8ff7e73b1d8d.png)
![image](https://user-images.githubusercontent.com/18277076/66631789-90508d80-ec39-11e9-9ec9-7c07206af38d.png)
![image](https://user-images.githubusercontent.com/18277076/66631926-e3c2db80-ec39-11e9-8d16-b965d2c7f8eb.png)
![image](https://user-images.githubusercontent.com/18277076/66632216-84b19680-ec3a-11e9-9839-684b2880d4ac.png)

The onnx model download from 
http://support.sas.com/documentation/prod-p/vdmml/zip/index.html
![image](https://user-images.githubusercontent.com/18277076/66632586-613b1b80-ec3b-11e9-8125-868a9ab59668.png)

enviroment:
![image](https://user-images.githubusercontent.com/18277076/66632462-22a56100-ec3b-11e9-95d2-4430830fc7df.png)
![image](https://user-images.githubusercontent.com/18277076/66632475-2802ab80-ec3b-11e9-9ee1-e4f720cae1a6.png)
![image](https://user-images.githubusercontent.com/18277076/66632493-2d5ff600-ec3b-11e9-8f56-f5c1939dc621.png)

**Comment by sasxianhu** [comment]
Again, use tiny-yolov2 as your output model table name.

**Comment by banbsyip** [comment]
> Again, use tiny-yolov2 as your output model table name.

i think it is maybe casued by problem 1:
NOTE: Model table is attached successfully!
NOTE: Model is named to "tiny_yolov2" according to the model name in the table.

**Comment by yg2288** [comment]
Hi @banbsyip,
For the first error, follow the steps below to handle the dataspecs / labels for importing the yolo model (do not use yoloweightsAttr.sashdat, since it contains the attributes for a different model - Pascal VOC)

Example:
```
# target variables
maxObjs = 5
targets = ['_nObjects_']
for i in range(maxObjs):
    targets.append('_Object%d_' % i)
    for sp in ["x", "y", "width", "height"]:
        targets.append('_Object%d_%s' % (i, sp)),
    
# input variables
inputVars = []
inputVars.insert(0, '_image_')

# data specs
data_spec = []
data_spec.append(DataSpec(type_='IMAGE',layer='image2',data=inputVars))
data_spec.append(DataSpec(type_='OBJECTDETECTION',layer='detection1',data=targets, nominals=['_Object%d_' % i for i in range(maxObjs)]))
```

Then, pass in `data_spec` when loading the h5 file:

```
model1.load_weights(path='/data/tiny_yolov2.onnxmodel.h5',
                   labels=True,
                    data_spec=data_spec,
                  label_file_name='/data/labels.csv', label_length=20)
```

where `labels.csv` specifies the class names:

```
label_id, label
0, "object0",
1, "object1",
2, "object2",
3, "object3",
4, "object4",
5, "object5"
```

For reference: https://github.com/sassoftware/python-dlpy/blob/master/dlpy/attribute_utils.py

Thanks

**Comment by yg2288** [comment]
@banbsyip I have attached the class labels here:
[tiny_yolov2_313cls_labels.txt](https://github.com/sassoftware/python-dlpy/files/3724328/tiny_yolov2_313cls_labels.txt)

Hope this helps!

**Comment by banbsyip** [comment]
> 9.778984, 5.595484, 2.98513, 3.924927, 11.580547, 11.534526, 5.183913, 8.863515, 1.09074, 1.433951



> Hi @banbsyip,
> For the first error, follow the steps below to handle the dataspecs / labels for importing the yolo model (do not use yoloweightsAttr.sashdat, since it contains the attributes for a different model - Pascal VOC)
> Example:
> # target variables
> maxObjs = 5
> targets = ['_nObjects_']
> for i in range(maxObjs):
>     targets.append('_Object%d_' % i)
>     for sp in ["x", "y", "width", "height"]:
>         targets.append('_Object%d_%s' % (i, sp)),
>     
> # input variables
> inputVars = []
> inputVars.insert(0, '_image_')
> 
> # data specs
> data_spec = []
> data_spec.append(DataSpec(type_='IMAGE',layer='image2',data=inputVars))
> data_spec.append(DataSpec(type_='OBJECTDETECTION',layer='detection1',data=targets, nominals=['_Object%d_' % i for i in range(maxObjs)]))
> 
> Then, pass in data_spec when loading the h5 file:
> model1.load_weights(path='/data/tiny_yolov2.onnxmodel.h5',
>                    labels=True,
>                     data_spec=data_spec,
>                   label_file_name='/data/labels.csv', label_length=20)
> 
> where labels.csv specifies the class names:
> label_id, label
> 0, "object0",
> 1, "object1",
> 2, "object2",
> 3, "object3",
> 4, "object4",
> 5, "object5"
> 
> For reference: https://github.com/sassoftware/python-dlpy/blob/master/dlpy/attribute_utils.py
> Thanks

thanks for your help. it maybe not caused by the dataspac, when i run the DLPy_Import_ONNX_Model.ipynb, the demo can be successful:
<img width="771" alt="image" src="https://user-images.githubusercontent.com/18277076/66903930-db9dde00-f035-11e9-8d50-280ed49ca165.png">
when i checked the yolo's code and the model's net, i found the output layer maybe wrong
<img width="732" alt="image" src="https://user-images.githubusercontent.com/18277076/66904133-2b7ca500-f036-11e9-8278-d3aba324feb8.png">

<img width="745" alt="image" src="https://user-images.githubusercontent.com/18277076/66904176-39cac100-f036-11e9-9120-3182978b208a.png">

**Comment by banbsyip** [comment]
I find the reason, when I change the output layer to the model, the model net as follows:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/18277076/67079030-09fdf380-f1c5-11e9-9e80-2063821c935c.png">
and the tiny_yolov2_weights.onnxmodel.h5 is:
![后](https://user-images.githubusercontent.com/18277076/67079128-331e8400-f1c5-11e9-82bc-d2591bd5547b.jpg)
the h5 file don't contain the last layer's weights, then i don't change the output layer of the model 
<img width="718" alt="image" src="https://user-images.githubusercontent.com/18277076/67079380-ac1ddb80-f1c5-11e9-8d61-08218492b49d.png">
<img width="774" alt="image" src="https://user-images.githubusercontent.com/18277076/67079409-b7710700-f1c5-11e9-85bc-91bbee83175b.png">
<img width="226" alt="image" src="https://user-images.githubusercontent.com/18277076/67079436-c48df600-f1c5-11e9-8f7f-733395d8a739.png">
<img width="738" alt="image" src="https://user-images.githubusercontent.com/18277076/67079614-159dea00-f1c6-11e9-90f2-7f2a8b240987.png">
so how can i add the yolo layer to the model ? @yg2288 @sasxianhu

**Comment by sasxianhu** [comment]
I am a little bit lost here. Are you following https://github.com/sassoftware/python-dlpy/blob/master/examples/onnx/DLPy_Import_ONNX_tinyYoloV2.ipynb?

If so, did you download your onnx model from here https://github.com/onnx/models?

tiny_yolov2_323cls is trained by SAS. We already provided the astore and onnx models as well as the sashdat formats. 

@yg2288 , have you tried to import our own ONNX back to Viya?

**Comment by banbsyip** [comment]
> I am a little bit lost here. Are you following https://github.com/sassoftware/python-dlpy/blob/master/examples/onnx/DLPy_Import_ONNX_tinyYoloV2.ipynb?
> If so, did you download your onnx model from here https://github.com/onnx/models?
> tiny_yolov2_323cls is trained by SAS. We already provided the astore and onnx models as well as the sashdat formats.
> @yg2288 , have you tried to import our own ONNX back to Viya?

my environment is dlpy1.1,the onnx model from https://github.com/onnx/models is unfit ,my onnx model download from http://support.sas.com/documentation/prod-p/vdmml/zip/index.html. when I followed the code from https://github.com/sassoftware/python-dlpy/blob/master/examples/onnx/DLPy_Import_ONNX_tinyYoloV2.ipynb,the tiny_yolov2_weights.onnxmodel.h5 lose the output layer's weights, the detail showed in the pictures above.
![image](https://user-images.githubusercontent.com/18277076/67368991-d519e400-f5aa-11e9-8d00-0081612d16cd.png)

**Comment by yg2288** [comment]
Hi @banbsyip ,
Attached please find the notebook and labels files for importing this onnx model, let me know if you run into any issues.  I ran this using dlpy 1.1.2 and onnx 1.5.0.

Thanks

[yolo_files.zip](https://github.com/sassoftware/python-dlpy/files/3763419/yolo_files.zip)

**Comment by ethem-kinginthenorth** [comment]
closing this issue for now. @banbsyip please do let us know if you have any further issues and questions. thanks.
