### ISSUE TITLE
Tiny_YoloV2 model issues for larger images with height and width provided. 

### ISSUE THREAD

**Issue by sasbsg** [sassoftware/python-dlpy#234]
I have noticed a strange error that depends on whether the height and width are provided in a Tiny_YoloV2 model.  In my case, I had a set of images that were larger than a 416x416 pixels. When I failed to include the dimensions in the model, I can get the fit method to execute.  When I include the dimensions, I generate an error that I am including below:

from dlpy.applications import Tiny_YoloV2
yolo_model = Tiny_YoloV2 (sess,
                         n_classes=12,
                         model_table="my_yolo_model",
                         #grid_number=13,
                         height=1944, width=2592,
                         predictions_per_grid=5,
                         anchors = yolo_anchors,
                         max_boxes=100,
                         coord_type=coord_type,
                         max_label_per_image=100,
                         class_scale=1.0,
                         coord_scale=1.0,
                         prediction_not_a_object_scale=1,
                         object_scale=5,
                         detection_threshold=0.35,
                         iou_threshold=0.05)
yolo_model.fit(data=dict(name='trainset', where='_nObjects_ > 0'),
              optimizer=optimizer,
              data_specs=data_specs,
              n_threads=1,
              record_seed = 13309,
              force_equal_padding=True
              #gpu=gpu
              )

NOTE: Training from scratch.
---------------------------------------------------------------------------
SWATError                                 Traceback (most recent call last)
<ipython-input-18-5cc5f9737f94> in <module>
      6               n_threads=1,
      7               record_seed = 13309,
----> 8               force_equal_padding=True
      9               #gpu=gpu
     10               )

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dlpy/model.py in fit(self, data, inputs, target, data_specs, mini_batch_size, max_epochs, log_level, lr, optimizer, nominals, texts, target_sequence, sequence, text_parms, valid_table, valid_freq, gpu, attributes, weight, seed, record_seed, missing, target_missing, repeat_weight_table, force_equal_padding, save_best_weights, n_threads, target_order)
    287                        force_equal_padding=force_equal_padding, init_weights=init_weights, target_order=target_order,
    288                        best_weights=self.best_weights, model=self.model_table, n_threads=n_threads,
--> 289                        model_weights=dict(replace=True, **self.model_weights.to_table_params()))
    290 
    291         try:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dlpy/model.py in train(self, table, attributes, inputs, nominals, texts, valid_table, valid_freq, model, init_weights, model_weights, target, target_sequence, sequence, text_parms, weight, gpu, seed, record_seed, missing, optimizer, target_missing, best_weights, repeat_weight_table, force_equal_padding, data_specs, n_threads, target_order)
    687                               target_order=target_order)
    688 
--> 689         rt = self._retrieve_('deeplearn.dltrain', message_level='note', **parameters)
    690 
    691         if rt.severity < 2:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dlpy/network.py in _retrieve_(self, _name_, message_level, **kwargs)
    271     def _retrieve_(self, _name_, message_level='error', **kwargs):
    272         ''' Call a CAS action '''
--> 273         return self.conn.retrieve(_name_, _messagelevel=message_level, **kwargs)
    274 
    275     @classmethod

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/swat/cas/connection.py in retrieve(self, _name_, **kwargs)
   1690         try:
   1691             # Call the action and compile the results
-> 1692             signature = self._invoke_with_signature(a2n(_name_), **kwargs)
   1693             results = self._get_results(getnext(self, datamsghandler=datamsghandler),
   1694                                         responsefunc=responsefunc, resultfunc=resultfunc)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/swat/cas/connection.py in _invoke_with_signature(self, _name_, **kwargs)
   1169             self._merge_param_args(signature.get('params', {}), kwargs, action=_name_)
   1170 
-> 1171         self._invoke_without_signature(_name_, **kwargs)
   1172 
   1173         return signature

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/swat/cas/connection.py in _invoke_without_signature(self, _name_, **kwargs)
    943         '''
    944         if isinstance(self._sw_connection, rest.REST_CASConnection):
--> 945             errorcheck(self._sw_connection.invoke(a2n(_name_), kwargs),
    946                        self._sw_connection)
    947         else:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/swat/cas/rest/connection.py in invoke(self, action_name, kwargs)
    437                     raise SWATError(self._results['error'])
    438                 else:
--> 439                     raise SWATError('Unknown error')
    440         except ValueError as exc:
    441             raise SWATError(str(exc))

SWATError: Unknown error

**Comment by ethem-kinginthenorth** [comment]
can you please also paste your create_object_detection call here? thanks
As a side note, yolo only works with square sizes - this is one thing we can add a warning message

**Comment by ethem-kinginthenorth** [comment]
@sasbsg did it work with square image sizes? thanks
