### ISSUE TITLE
Trouble Loading model weights

### ISSUE THREAD

**Issue by JesseRLund** [sassoftware/python-dlpy#241]
I'm using a standard image classification script and in my new environment I am getting the following errors when I try to load the caffe model. I have tried both a resnet50 and vgg16. I've also checked permissions on the directory I put them in. This script has worked in other environments without this issue.

model_vgg16 = VGG16(
    conn, model_table='VGG16_notop',
    n_classes=3, 
    n_channels=3, 
    width=224, 
    height=224, 
    scale=1,
    offsets=trainData.channel_means,
    pre_trained_weights=True, 
    pre_trained_weights_file=dir_path + 'VGG_ILSVRC_16_layers.caffemodel.h5',
    include_top=False
    )   

NOTE: no dataspec(s) provided - creating image classification model.
NOTE: Model weights attached successfully!
ERROR: The specified CASLIB is not a path-type CASLIB.
ERROR: The action stopped due to errors.
NOTE: Model table is attached successfully!
NOTE: Model is named to "vgg16_notop" according to the model name in the table.
ERROR: Could not connect to the Hadoop cluster.
ERROR: Table 'vgg16_notop_weights' could not be loaded.
ERROR: Failure opening table 'vgg16_notop_weights': A table could not be loaded.
ERROR: The action stopped due to errors.

**Comment by ethem-kinginthenorth** [comment]
does the server have access to the dir_path? would you please elaborate on this a bit more "This script has worked in other environments without this issue."? thanks.

**Comment by JesseRLund** [comment]
Yes. The server has access to that path. The last statement is unimportant. I was just referring to the fact that in the past I've been able to use the code to load pre-trained weights. Thanks.

**Comment by ethem-kinginthenorth** [comment]
Cool. but if we now what was different we could help. are you using the server in smp mode or mpp mode?

**Comment by JesseRLund** [comment]
We resolved this issue by saving the .h5 file to a non-distributed file system. Thanks for your help!
