### ISSUE TITLE
Image Captioning Example

### ISSUE THREAD

**Issue by pynyah** [sassoftware/python-dlpy#243]
Hi ,

I am facing issues with the output of below cells. It is not in alignment with what has been shown in the example. Can you please look into it?
![image](https://user-images.githubusercontent.com/54321951/68127350-b963f580-ff3b-11e9-93ea-83acfca35787.png)

Appreciate your help

**Comment by sasxianhu** [comment]
what does your word_embedding table look like?

**Comment by ethem-kinginthenorth** [comment]
@pynyah any update on this issue?

**Comment by ethem-kinginthenorth** [comment]
@pynyah , I am closing this issue, please do re-open the issue if you have any further issues. thanks
