### ISSUE TITLE
TextClassification reset weights

### ISSUE THREAD

**Issue by fede-citti** [sassoftware/python-dlpy#245]
**Is there a way to reset the weights in a TextClassification application?**

I have the following situation:
Define model1:
`model1 = TextClassification(s, neurons=10, n_blocks= 3, rnn_type='GRU')`
Train it:
 `model1.fit(data=trainData, inputs='text', texts='text', target='target_new',
               text_parms=TextParms(init_input_embeddings='wiki_embeddings'),
               mini_batch_size=1, 
               max_epochs=50, 
               lr=0.1, 
               log_level=2,
               valid_table=validData)`
Define a new model:
`model2 = TextClassification(s, neurons=10, n_blocks= 3, rnn_type='GRU')`
then model2 inherits the same weights as model1, that's not what I want.

**Comment by sasxianhu** [comment]
can you use another model_table name? The default is 'text_classifier'.

**Comment by sasxianhu** [comment]
can you use another model_table name? The default is 'text_classifier'.

**Comment by sasxianhu** [comment]
can you use another model_table name? The default is 'text_classifier'.

**Comment by fede-citti** [comment]
Thanks, the issue is solved
