### ISSUE TITLE
'get_anchors' method assumes square images?

### ISSUE THREAD

**Issue by mikejenista** [sassoftware/python-dlpy#248]
When I create training data for object detection, the 'create_object_detection_table' method allows me to specify a 2-tuple with both dimensions of my images.  But when I use the 'get_anchors' method with coco coordinates, I have to specify the image size as a single integer.  Does the yolo algorithm assume square images?  Or should 'get_anchors' also support 2-tuples to specify both dimensions?

**Comment by ethem-kinginthenorth** [comment]
yolo does not accept non-square images for now. I believe there is an warning / note should popup when you try to create yolo with non square images. FasterRCNN is the only object detection algorithm that accepts non-square images for now.

**Comment by mikejenista** [comment]
thanks
