### ISSUE TITLE
Loading Tiny YOLOv2 for Inference

### ISSUE THREAD

**Issue by formulajuan** [sassoftware/python-dlpy#256]
Hi,

I've trained a single class object detector using the Tiny YOLO model. I used the documentation here on GitHub as well as [the SAS documentation](https://documentation.sas.com/?docsetId=casdlpg&docsetTarget=p1np8zbnoyd0brn1dhehthuuxj4q.htm&docsetVersion=8.3&locale=en#n0h67hfe9mx1byn122dvmb7fm8zn) as a guide.

After training the model I used the `s.save` function to save both the weights & attributes for later use. In a new session I've been struggling to load the model+weights and make an inference on some images - I've tried to use `model.predict` and `s.dlScore` but both produce the same error. 

Here's my code for the model.predict approach:

```
from dlpy.applications import Tiny_YoloV2

obj_anchors = (4.433616955826258, 0.8040793768832574, 
               3.4978464472650543, 0.6520535862178309, 
               2.7876855046331777, 0.4014445793224864, 
               1.6768336147472485, 0.46881804174965, 
               3.123764957760637, 0.5228782337714222)

obj_detection_model = Tiny_YoloV2(s, 
                                  n_classes=1, 
                                  predictions_per_grid=5, 
                                  anchors = obj_anchors,
                                  max_boxes=100,
                                  coord_type='yolo',
                                  max_label_per_image = 1,
                                  class_scale=1.0, 
                                  coord_scale=1.0, 
                                  prediction_not_a_object_scale=1, 
                                  object_scale=5,
                                  detection_threshold=0.2, 
                                  iou_threshold=0.2)

obj_detection_model.set_weights('yolov2TrainedWeights_tiny_ctr')

from dlpy.images import ImageTable

predict_tbl = ImageTable.load_files(conn=s, path="/random_imgs/", casout=dict(name='Test_Images'))

predict_tbl.resize(height=416, width=416, inplace=True)

obj_detection_model.predict(data='Test_Images')
```

![image](https://user-images.githubusercontent.com/57802244/69547417-779ffb00-0f8d-11ea-8aec-1da0ff431dd1.png)

Using the dlScore action on an ImageTable containing 416x416 images produces the same error ('Test_Model' is a CAS table containing the same model architecture as above):

```
s.dlscore(model='Test_Model', 
          initWeights='yolov2TrainedWeights_tiny_ctr',          
          table = 'Test_Images_Resized',
          copyVars=['_image_'],           
          nThreads=10,
          miniBatchSize=1,
          loglevel=2,
          casout={'name':'detections', 
                  'replace':True
                  }
          )
```

![image](https://user-images.githubusercontent.com/57802244/69547332-4aebe380-0f8d-11ea-8671-2d1df2ec110a.png)

I don't think I've loaded the weights/architecture correctly for inference but can't find any similar examples.

**Comment by sasxianhu** [comment]
When you load the model weight table, do you specify  loadAttrs=True?
If you use DLPy, when saving models, better use model.deploy.

**Comment by sasxianhu** [comment]
BTW: if you call model.deploy to save the model as sashdat, you can call model.load_weights to load it back. load_weights will load both weights and the model attributes.

**Comment by formulajuan** [comment]
Neither model.set_weights or s.dlscore have an option to flag loadAttrs as true.
Do I need to retrain the model to get the architecture, weights, and attributes all together before calling model.deploy?

**Comment by formulajuan** [comment]
Also, my use case is to make an initial prediction on an image and crop it to leave only the highest confidence object before processing the image further. Do either the model.predict or s.dlscore functions return coordinates of object predictions on test images so I can manually extract the objects from the input image?

**Comment by sasxianhu** [comment]
After you save the model, how do you load the table back? loadAttrs is one of options for the loadTable action. 
model.predict indeed returns the predicted bounding boxes with the confidence. If you want to use the action to extract all the objects, you can try image.extractDetectedObjects with extractType="CROP".

**Comment by formulajuan** [comment]
> After you save the model, how do you load the table back?

I have been loading the weights table from SAS Data Explorer to load it into the active caslib before calling model.set_weights and passing the name of the weights table.

> model.predict indeed returns the predicted bounding boxes with the confidence. If you want to use the action to extract all the objects, you can try image.extractDetectedObjects with extractType="CROP".

That's great, thanks!

**Comment by sasxianhu** [comment]
Data Explorer does not load the attrs, I think. Can you try model.load_weights to load it?
I assume you called s.save with saveAttrs=True.

**Comment by formulajuan** [comment]
I used s.save twice as the SAS documentation does, seemingly saving both the weights and attrs as 2 separate sashdat files.

![image](https://user-images.githubusercontent.com/57802244/69550592-2c88e680-0f93-11ea-9d96-28951f838241.png)

I had been using model.set_weights instead of model.load_weights because there is no local copy of the sashdat file to use with model.load_weights, it is only stored on the server side.

**Comment by formulajuan** [comment]
Is the best option to just retrain the model and use model.deploy after training to save the weights locally? That way they can be loaded by calling model.load_weights like you suggested.

**Comment by sasxianhu** [comment]
model.load_weights actually read the files from the server.
If you really want to use your current weights, here are the manual steps:
1. load the stored attrs table as well.
2. attach attrs with this:
s.table.attribute(caslib='CASUSER(xxxx)', task='ADD', name='your_model_table_name', attrtable='the_attrs_table_name')

I assume you use casuser as your caslib. Both tables are under casuser.

**Comment by formulajuan** [comment]
I think I will retrain and use model.deploy as you suggested since that seems to be better than the s.save method for weights/attrs as in the other SAS documentation. 

If I retrain and use model.deploy with an output format of castable does that mean the weights are saved in the current caslib so I can call them using model.load_weights? [The DLPy documentation](https://sassoftware.github.io/python-dlpy/generated/dlpy.model.Model.deploy.html) says the "path" option for model.deploy specifies a client-side path, which is why I assumed load_weights read the file from client side as well.

**Comment by sasxianhu** [comment]
If you store your model as the astore model, it has to be a client-side path since this model will be downloaded to your local client side.
If you store your model as sashdat, it stays on the server side.
DLPy APIs wrap up all the actions to simply the process. But it is still good to play with the action-level codes to get better understanding about what happens under the hood. And the SAS documentation mainly focuses on the action interface. This is why it shows you how to use save to store the model weights and the attrs.

**Comment by sasxianhu** [comment]
@ethem-kinginthenorth , please update the DLPy doc as well for model.deploy.

**Comment by formulajuan** [comment]
> If you store your model as the astore model, it has to be a client-side path since this model will be downloaded to your local client side.
If you store your model as sashdat, it stays on the server side.

Thanks for clarifying - I was unsure about this. I will go ahead and use model.deploy and that should hopefully fix my issues for the time being.
Thanks for your help!

**Comment by sasxianhu** [comment]
Let me know how it goes. If you encounter other issues, please either reopen this or create a new issue.

**Comment by teoland** [comment]
Adding on the previous thread, the initial error message "Invalid argument" that was received from the dlscore was not really helpful. Will it be possible to add a specific error message when weight attributes are missing? The same goes for the .predict method.

Thanks!

**Comment by sasxianhu** [comment]
Yes, I indeed polished the message for Viya 3.5 with this:
The model table cannot be loaded successfully. Please check whether the table is complete such as including the table attributes.

**Comment by teoland** [comment]
That's great! Thank you

**Comment by formulajuan** [comment]
Hi, the model.deploy method works fine and I can deploy and load the model in a new session for inference as expected. 

However I was wondering if it's possible to change the name of the output CAS table before calling model.deploy, because their names after deploying conflict with the pretrained weights files used initially to train the model that are stored in the working caslib?

For reference, I am able to deploy like this:

![image](https://user-images.githubusercontent.com/57802244/69872232-c52da800-12ac-11ea-864a-49ca19a20b72.png)
 
But the 3 files that are saved after deploying conflict with the pretrained ones already stored on the server and they can't be renamed on Data Explorer:

![image](https://user-images.githubusercontent.com/57802244/69872298-f0b09280-12ac-11ea-82b0-362c8715b9ed.png)

**Comment by sasxianhu** [comment]
when you call TinyYoloV2 to create your model, you can use model_table to specify a different model name.

**Comment by formulajuan** [comment]
Thank you!
