### ISSUE TITLE
Add examples about Keypoints 

### ISSUE THREAD

**Issue by sasxianhu** [sassoftware/python-dlpy#26]

**Comment by aviolante** [comment]
@sasxianhu @ethem-kinginthenorth I should be starting a project around this hopefully next week!

**Comment by ethem-kinginthenorth** [comment]
@aviolante that sounds great

**Comment by wenyushi** [comment]
The issue should be closed.

**Comment by ethem-kinginthenorth** [comment]
we have added and example. @wenyushi and @kybowm thanks.
