### ISSUE TITLE
Caslib Permissions Error

### ISSUE THREAD

**Issue by formulajuan** [sassoftware/python-dlpy#267]
Hi,

I've been using a trial Viya environment which was due to expire last week but we had the license extended for a few weeks. Since the license was extended some of the code I had written before to access models stored in the 'PUBLIC' caslib has been producing permissions errors. It seems to have lost read/write access to the caslib meaning I can't use functions such as `Model.from_sashdat` to load models into memory or `Model.deploy` to save them permanently in the caslib.

For example, using either of the above functions to load/deploy a model to the 'PUBLIC' caslib produces the following error:

![image](https://user-images.githubusercontent.com/57802244/72803475-196a5e00-3c46-11ea-9490-23d8f11df915.png)

I can still create temporary cas tables when PUBLIC is the active caslib, for example loading a locally-stored model into CAS, or uploading a Pandas dataframe, or loading images into an ImageTable. The issue seems to be accessing models that are permanently stored in the caslib.

Thanks!

**Comment by sasxianhu** [comment]
Could you run table.caslibInfo with verbose=True and paste your results here? This action returns the caslib information.

**Comment by formulajuan** [comment]
| Name | Type | Description | Path | Definition | Subdirs | Local | Active | Personal | Hidden | Transient
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | CASUSER(viyademo01) | PATH | Personal File System Caslib | /home/viyademo01/casuser/ |   | 1.0 | 0.0 | 0.0 | 1.0 | 0.0 | 1.0
1 | Formats | PATH | Stores user defined formats. | /opt/sas/viya/config/data/cas/default/formats/ |   | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
2 | ModelPerformanceData | PATH | Library for Model Management performance objects. | /opt/sas/viya/config/data/cas/default/modelMon... |   | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
3 | Models | PATH | Stores models created by Visual Analytics for ... | /opt/sas/viya/config/data/cas/default/models/ |   | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
4 | Public | PATH | Shared and writeable caslib, accessible to all... | /opt/sas/viya/config/data/cas/default/public/ |   | 0.0 | 0.0 | 1.0 | 0.0 | 0.0 | 0.0
5 | Samples | PATH | Stores sample data, supplied by SAS. | /opt/sas/viya/config/data/cas/default/samples/ |   | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
6 | SystemData | PATH | Stores application generated data, used for ge... | /opt/sas/viya/config/data/cas/default/sysData/ |   | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0

**Comment by sasxianhu** [comment]
Not sure you have permissions to manage caslibs. 

If you are the only user for this system, you could try these:

1. drop PUBLIC: 
table.dropCaslib(caslib='public')
2. add it back with  subDirectories=True:
table.addCaslib(activeonadd=True,datasource={'srctype':'path'},
                  name='dnfs',path='/opt/sas/viya/config/data/cas/default/public/',
                  subdirectories=True)

A better way is to use CASUSER as your active caslib. PUBLIC seems in default having a strict permission about subdirs. This can be configured for sure when you start your cas.

**Comment by formulajuan** [comment]
Yeah I don't have the permission to manage the caslibs so I can't drop and add it back. Using the CASUSER caslib would definitely have been better but I deployed my trained models to PUBLIC so I only ran into difficulty after trying and failing to load models from that caslib.

**Comment by sasxianhu** [comment]
In some cases, we do need subdirs=True. For your case, it is not required. @ethem-kinginthenorth is working on a quick fix by returning a warning not error.

**Comment by ethem-kinginthenorth** [comment]
yep. running the unit tests now.

**Comment by ethem-kinginthenorth** [comment]
@formulajuan, are you using a local version of dlpy (git cloned to your local), right?

**Comment by formulajuan** [comment]
That's right, I'm currently using dlpy version 1.1.3-dev.

**Comment by ethem-kinginthenorth** [comment]
@formulajuan can you please update your local copy and try again to see if it works with the changes we have just made. thanks

**Comment by formulajuan** [comment]
The latest version I could get is still 1.1.3-dev, I tried to update and the error was the same.

**Comment by ethem-kinginthenorth** [comment]
did you do another git pull in your local copy?

**Comment by HaidarAltaie** [comment]
Working alongside @formulajuan  on this - We used "pip install git+https://github.com/sassoftware/python-dlpy.git@master --user" to obtain the 1.1.3-dev version, is that the appropriate step since re-running causes the same issue.

**Comment by ethem-kinginthenorth** [comment]
I will be pushing one more change, if that won't help, we will consider other ways. stay tuned. thanks

**Comment by ethem-kinginthenorth** [comment]
I have just made another push. would you please grab it. let's see if this works. If not, we might want to try removing and installing dlpy again. Perhaps we can also analyze a couple of lines in the source code on the client machine to make sure our changes is reflected. thanks

**Comment by formulajuan** [comment]
I tried to update again this morning using the method @HaidarAltaie mentioned above and the error message remained the same when trying to load a model from PUBLIC.

**Comment by sasxianhu** [comment]
Did you restart the kernel if you use notebook?

Best,
XQ

Everyday is a new learning day.
________________________________

**Comment by formulajuan** [comment]
Yeah I did, I've tried updating dlpy from Jupyter and MobaXterm with no luck.

**Comment by sasxianhu** [comment]
The fix just changes the error to warning if you check the message in  https://github.com/sassoftware/python-dlpy/blob/master/dlpy/utils.py. It doesn't sound the fix is picked up. Is it ok to upload your notebook?

**Comment by formulajuan** [comment]
I was able to get the latest commit by adding `--upgrade` to the pip install command from Jupyter, the change from error to a warning made by @ethem-kinginthenorth works now and I'm able to load the model from PUBLIC successfully, thanks!

**Comment by sasxianhu** [comment]
Great. And thanks for sharing the --upgrade flag. Let us know if you have other issues. Close this for now.
