### ISSUE TITLE
Recursively use "create_object_detection_table"

### ISSUE THREAD

**Issue by fede-citti** [sassoftware/python-dlpy#271]
Is it possible to use the "create_object_detection_table" function recursively on subfolders? 
We have our data in this structure:
Image1
    -001.xml
    -001.jpg
    -002.xml
    -002.jpg
Image2
    -001.xml
    -001.jpg
    ...

**Comment by sasxianhu** [comment]
I don't think we support this structure after I checked create_table_from_pascal_voc_format in https://github.com/sassoftware/python-dlpy/blob/master/dlpy/utils.py. Of course, it is doable to add a new option to support the recursive way.

**Comment by bensloane** [comment]
Quick question here... What is the use case for having split annotations in subdirectories?I thought the annotation files should keep track of all the objects in a single image. 

That being said I can help implement this if there is interest.

**Comment by fede-citti** [comment]
The case is that here we have huge medical images (more than 30000x30000 pixels) coming from different patients. Since the objects that we want to detect are small compared to the entire images, we have split them into a grid and we want to do object detection on the smaller pieces. 
That's why we have the main folders with the patient ID and the subfolders with the splitted images

**Comment by sasxianhu** [comment]
@bensloane , feel free to work on this when you have time.
