### ISSUE TITLE
Yolo models should throw an error if non-square input is not supported

### ISSUE THREAD

**Issue by smatton** [sassoftware/python-dlpy#279]
model = YoloV2(s, yolo_anchors, width=224, height=74)    

Does not throw an error with non-square input. When running fit method you get this error.
ERROR: The source layer to the detection layer contains an incompatible number of neurons.
ERROR: The action stopped due to errors.

If non-square input is not supported can we throw an error?

**Comment by ethem-kinginthenorth** [comment]
Which version of dlpy you have? I remember I added some sort of a check and a warning message to prevent this. Let me-recheck the source code.

**Comment by ethem-kinginthenorth** [comment]
this is the source code on the github version:
if input_parameters['width'] != input_parameters['height']:
        print(not_supported_feature('Non-square yolo model training', 'height=width'))
        input_parameters['height'] = input_parameters['width']

so I we should be adjusting non-square input sizes

**Comment by smatton** [comment]
1.1.2. I thought it could be that so I did conda update sas-dlpy. I also spun up fresh conda environment in docker and installed dlpy to confirm version you get with conda install is 1.1.2. For now I will just work around it until conda gets the changes.

**Comment by ethem-kinginthenorth** [comment]
Possibly, it is still in the code but not released. With the next release it should be there.
