### ISSUE TITLE
dlpy.applications.Faster_RCNN backbone valid values

### ISSUE THREAD

**Issue by Mespith** [sassoftware/python-dlpy#281]
This is a very minor issue I think, but I saw that in the documentation of [dlpy.applications.Faster_RCNN](https://sassoftware.github.io/python-dlpy/generated/dlpy.applications.Faster_RCNN.html) that the valid values for the backbone variable is only "vgg16". When I checked the code of this model I saw a lot more possible values: vgg16, resnet50, resnet34, resnet18, mobilenetv1 and mobilenetv2.

Could this be changed in the documentation please? :)

**Comment by sasxianhu** [comment]
This is already fixed in our dev branch:

https://github.com/sassoftware/python-dlpy/blob/master/dlpy/applications/rcnn.py


backbone: string, optional
        Specifies the architecture to be used as the feature extractor.
        Valid values: vgg16
        Default: vgg16, resnet50, resnet18, resnet34, mobilenetv1, mobilenetv2
