### ISSUE TITLE
Axis question in the heat_map_analysis

### ISSUE THREAD

**Issue by staceychan** [sassoftware/python-dlpy#288]
Hi teams,

I have a question about the heat_map_analysis.
The axis of the heat map is from red to blue and the number is getting higher.
I'm wondering that the red color should mean the higher temperature.
Is there any information about this? 
Thanks for your help! :)

here is an example image
![擷取](https://user-images.githubusercontent.com/35584966/76393344-533a2400-63ae-11ea-9690-1f5d001e2d32.JPG)

**Comment by sasxianhu** [comment]
The red regions mean it is important to make the prediction.

**Comment by staceychan** [comment]
Thanks for your replying!
But I still confuse about the number on the right side.
Does it mean the level of the importance?

**Comment by wenyushi** [comment]
Axis represents the probability of ground-truth class. Basically, heat map analysis uses a black map to cover a region on your image. If the region is essential, the confidence of the blocked image is expected to drop a lot.

**Comment by sasxianhu** [comment]
https://github.com/sassoftware/python-dlpy/blob/master/dlpy/model.py

line 2318: it calculates the mean predicted probability if you cover a region with a black map.  When it is lower, it means that region is important in terms of making predictions.

**Comment by staceychan** [comment]
I got it!
Thanks for your help :)
