### ISSUE TITLE
ONNX model output to onnxruntime

### ISSUE THREAD

**Issue by staceychan** [sassoftware/python-dlpy#294]
Hi expert,

I'm working on a project, in which we have to use VDMML to train a image classification model and deploy to an edge device.

We don't have esp edge, so I want to output the model as onnx and use onnxruntime at the edge device.

From my perspective, I can load the onnx model and then input the image array directly.
But it came out like the picture below.
![image](https://user-images.githubusercontent.com/35584966/78960938-36664d00-7b22-11ea-931c-93c198bb4136.png)
The output is nan. 

So I wondering is there any possible I have to do or be careful when outputing the onnx model?
Or is there any example for this kind of application? 
Thanks!

**Comment by wenyushi451** [comment]
Can you please do one experiment running the onnx model on either pytorch or tensorflow and see if you get similar results?

**Comment by staceychan** [comment]
Hi wenyu,

Thanks for replying!
I've tried to builed the same network by pytorch and convert it to onnx.
it works, so i will keep trying if there's any possible problem in my code or the input/output type.

Thanks! 
It would be great if there are some examples similar to this.
