### ISSUE TITLE
Keras Little Endian model into SAS Big Endian platform

### ISSUE THREAD

**Issue by antoajayraj** [sassoftware/python-dlpy#296]
If I have a Keras model generated on a Little Endian platform. Can that be imported seamlessly into the SAS Viya which runs on a Big Endian platform ?

**Comment by eusdougc** [comment]
@antoajayraj - The best answer I can give is "maybe" as I don't think any of our developers have tried this.  We rely in part on Keras, so if Keras does not support your scenario, then we won't either.  If you have a way of testing, could I suggest running [this](https://github.com/sassoftware/python-dlpy/blob/master/examples/keras_model_conversion/Import_Keras_LeNet.ipynb) example and seeing if you get the correct results?  Here I am assuming that your Viya client computer is the little endian part of your scenario while the Viya server computer is the big endian part of your scenario.

**Comment by eusdougc** [comment]
@antoajayraj - have you tried the example I suggested?

**Comment by eusdougc** [comment]
Closing issue as there has been no feedback from @antoajayraj.
