### ISSUE TITLE
Deploy astore on the server-side

### ISSUE THREAD

**Issue by staceychan** [sassoftware/python-dlpy#303]
Hi expert,

According to the ducument, I found that I cannot deploy the astore model to the server-side.
https://sassoftware.github.io/python-dlpy/generated/dlpy.model.Model.deploy.html

Is there any suggestion if I want to deploy astore from the client-side to the server-side?
Cause I want the model I deployed can be used in ESP, but now I have to deploy and then move it from client to server.

Thanks for your time :)

**Comment by eusdougc** [comment]
@staceychan - there is currently no way to deploy an astore model directly to the server unless there is common disk space that both can access.  For example, there might be one or more network drives that are mounted in such a way that both your client and your server can read/write to them.  In that case, you simply provide a client path to the common disk space and write the astore model there.  Then ESP can pick the astore model up directly using the server path to that same disk space.

**Comment by staceychan** [comment]
Hi Expert,

Thanks form your replying! :)
I'm going to close this issue.

Thanks again:)
