### ISSUE TITLE
Last cell in Auto Encoder example displays training images twice

### ISSUE THREAD

**Issue by TimoKettunenSAS** [sassoftware/python-dlpy#305]
I was following the auto encoder example and noticed that the last cell does not produce comparison between training and auto encoder images. It displays training images twice.

Could someone please modify the example to properly display images from the model.

https://github.com/sassoftware/python-dlpy/blob/master/examples/auto_encoder/auto_encoder.ipynb

**Comment by eusdougc** [comment]
@TimoKettunenSAS - please re-check the last cell.  This line

display_segmentation_images(conn, 'merged_table', n_images=5, image_column='_image_', 
                            segmentation_labels_table='merged_table', label_column='_label_')

displays 5 of the original images (note the image_column is the original _image_ variable).  The following line

display_segmentation_images(conn, 'merged_table', n_images=5, image_column='_image_output_', 
                            segmentation_labels_table='merged_table', label_column='_label_')

displays 5 of the corresponding images created by the autoencoder model.  Note that image_column is now _image_output_.  The previous cell had created that variable from the images predicted by the model.

**Comment by TimoKettunenSAS** [comment]
Could you please review the logic. I understand what that notebook is trying to do in cells 7, 8 and 9. What I'm trying to explain is that it does not work as intended.

Here's two screenshots. One from following cells 7,8 and 9 from the example notebook. Second one is created by extracting features from decoder layer and formatting the resulting array into an image.

As you can see, by following the example the images are identical. Like in the example notebook. The color order is wrong but that is a different issue.

When creating images from the features extracted from the decoder the result is what one would expect. Somewhat similar image but not 1-1 identical.

![notebook_example](https://user-images.githubusercontent.com/66490260/85344116-9888ea00-b4a3-11ea-8978-813fe3f1a86e.PNG)
![image_from_decoder](https://user-images.githubusercontent.com/66490260/85344118-99ba1700-b4a3-11ea-9adf-e4d3c772127f.PNG)

Br,
Timo

**Comment by eusdougc** [comment]
New autoencoder example has been created - closing issue.
