### ISSUE TITLE
ImageTable set label_col error

### ISSUE THREAD

**Issue by staceychan** [sassoftware/python-dlpy#312]
Hi Expert,

I'm try to reproduce the multitask learning code as example here \\sashq\root\data\DeepLearn\data\MIML\ipynb\MIML_example_Multitask_BN_Sigmoid.ipynb

I ran the code ImageTable.from_table and wanted to set label_col, but it seemed the label_col didn't change
like the figure below.
![image](https://user-images.githubusercontent.com/35584966/87380146-737c2880-c5c4-11ea-8d95-43764564313f.png)

My dlpy version is 1.2.0 

If there is any suggestion, please let me know.
Thanks a lot! :)

Best regards,
Stacey

**Comment by fede-citti** [comment]
Looking at the source code here https://github.com/sassoftware/python-dlpy/blob/master/dlpy/images.py (lines 906 -919) , it looks like it needs specifically a column called "_label_". i would rename the column to get label_freq.
Or adapt the source code to your variable name:
`out = self._retrieve('simple.freq', table=self, inputs=['_label_'])['Frequency']`

**Comment by eusdougc** [comment]
@staceychan - did the suggestion from @fede-citti solve your problem, or are you still having an issue?

**Comment by staceychan** [comment]
Hi Both,

Thanks for your replying!
I thought the label_col could be assigned, but it seeems it's fixed.

Thanks again! :)
