### ISSUE TITLE
ResNet Model deploy to ONNX

### ISSUE THREAD

**Issue by staceychan** [sassoftware/python-dlpy#318]
Hi Expert,

I'm trying to deploy viya model to onnx format and score on an open source device using onnxruntime.
I noticed that the method works when the architecture is VGG or InceptionV3.
But when I deployed ResNet model and loaded by onnxruntime there was an error
![image](https://user-images.githubusercontent.com/35584966/89390563-7c7e9680-d739-11ea-9476-b9ce9a40a185.png)

(I have tried ResNet50_Caffe, ResNet50_SAS and ResNet18_Caffe.)
I'm wondering if there any different between these model or any special layers?
Cause in the onnx model converted from pytorch works.

Thanks.

**Comment by eusdougc** [comment]
@staceychan  - the exception seems to be related to one of the pooling layers.  A kernel dimension for this pooling layer appears to be 0 (or less than 0).  Can you post the code that you used to deploy the ResNet model?  Also, what version of ONNX are you using?

**Comment by staceychan** [comment]
Hi Expert,

Thanks for your replying!
Here is the html file of how I generate the onnx file from viya
and also the onnxruntime code to load the model
my onnx version is 1.6.0 and onnxruntime is 1.3.0

[onnx_try.zip](https://github.com/sassoftware/python-dlpy/files/5038955/onnx_try.zip)

**Comment by staceychan** [comment]
Hi Expert,

I did some test and found that the onnx file generated by viya can be load into viya again when it is VGG16.
But it would fail when the model is ResNet
As the figures below.
Also the attachment is the html file of the source code
![image](https://user-images.githubusercontent.com/35584966/89767326-4c196c80-db2c-11ea-9674-b7c278752318.png)

![image](https://user-images.githubusercontent.com/35584966/89767410-723f0c80-db2c-11ea-8c6f-10e4b46ab7cb.png)
[Mnist_Example_Export_Import.zip](https://github.com/sassoftware/python-dlpy/files/5049890/Mnist_Example_Export_Import.zip)
