### ISSUE TITLE
Load weight fails if environment contains a database caslib

### ISSUE THREAD

**Issue by ldepaula3** [sassoftware/python-dlpy#330]
**On this project I am using the BERT module.**

**After compiling the model, on the step of migrating the kerasmodel.h5 to the server and calling load_weights on the fully qualified name path, it fails with this error:**

`Warning: /home/myTmp/bert-base-uncased.kerasmodel.h5 is the subpath of the caslib, Oracle. Your action might not be completed successfully as you don't have permission to access the subdirectory of the caslib. To make the directory accessible from CAS, you can recreate the caslib, Oracle, by calling addCaslib action, and set option subDirectories to True
ERROR: The connection to the data source driver failed.
ERROR: General error ORA-12514: TNS:listener does not currently know of service requested in connect descriptor
ERROR: Function failed.
ERROR: The action stopped due to errors.

DLPyError                                 Traceback (most recent call last)
<ipython-input-10-a3d805dd7c14> in <module>
      4                   # Do not freeze base model weights.
      5                   # Allow layer updates with model tuning.
----> 6                   freeze_base_model=False)
~/.local/lib/python3.6/site-packages/dlpy/transformers/bert_model.py in load_weights(self, path, num_target_var, freeze_base_model, use_gpu, last_frozen_layer)
    965                                              data_spec=data_spec,
    966                                              use_gpu=use_gpu,
--> 967                                              embedding_dim=self._config['hidden_size'])   
    968 
    969         # determine which layers to freeze
~/.local/lib/python3.6/site-packages/dlpy/network.py in load_weights(self, path, labels, data_spec, label_file_name, label_length, use_gpu, embedding_dim)
    978         '''
    979         if not file_exist_on_server(self.conn, path):
--> 980             raise DLPyError('The file, {}, doesn\'t exist on the server-side.'.format(path))
    981 
    982         server_sep = get_server_path_sep(self.conn)
DLPyError: The file, /home/myTmp/bert-base-uncased.kerasmodel.h5, doesn't exist on the server-side.`

**Here is what the code looks like**

`bert.load_weights(path='/home/myTmp/bert-base-uncased.kerasmodel.h5', 
                  num_target_var=num_tgt_var, 
                  # Do not freeze base model weights.
                  # Allow layer updates with model tuning.
                  freeze_base_model=False)`

**Apparently SAS tries to create a temporary CASLIB on the absolute path of the h5 file.**

**After I deleted the Oracle CASLIB for my user it worked, but this is not ideal.**

**Comment by dxq77dxq** [comment]
When you create the Oracle caslib, please add option subdirectories=True and see if it helps.

**Comment by eusdougc** [comment]
@dxq77dxq - the problem @ldepaula3 describes is indeed a bug.  I walked through his setup with him and identified what was going wrong.

**Comment by eusdougc** [comment]
This issue has been resolved with pull request #356.
