### ISSUE TITLE
Ability to add custom loss in OutputLayer

### ISSUE THREAD

**Issue by JulianMar11** [sassoftware/python-dlpy#332]
For class imbalance it is sometimes necessary to pass a custom loss function or a weighted loss. Especially for detection and segmentation, imbalance cannot be handled via sampling strategies.

**Comment by dxq77dxq** [comment]
Hi Julian,
While there is no pre-defined weighted loss, we do support FCMP type of loss, which is a user-defined loss function. You can write your own loss function with parameter fcmpAct and fcmpErr.

**Comment by dxq77dxq** [comment]
Hi Julian,

Please let me know if it solves the problem and we can go ahead closing this issue.

Thanks,
Maggie

**Comment by eusdougc** [comment]
@JulianMar11  - there is an example in the SAS documentation that shows how to define and use both a custom activation and a custom loss function.  Please see [this](https://go.documentation.sas.com/?docsetId=casdlpg&docsetTarget=n09hd6k2q73oa6n15mvm17dvtuqt.htm&docsetVersion=8.3&locale=en#n10en2lf5u7nusn1xxuvoca81pu5) page.

**Comment by eusdougc** [comment]
@JulianMar11 - did the documentation page help with your question?

**Comment by eusdougc** [comment]
No further feedback from @JulianMar11 - closing.
