### ISSUE TITLE
heat_map_analysis without ground truth label

### ISSUE THREAD

**Issue by staceychan** [sassoftware/python-dlpy#333]
Hi experts,

I noticed that we need the ground truth label to generate the heat map in our dlpy "heat_map_analysis" function.
Is there any function we can use to generate the heat map of a new testing image without ground truth label?

Thanks!

**Comment by dxq77dxq** [comment]
Hi Stacey,

The heat maps are calculated based on the probability of the correct class, which means ground truth labels are necessary. 

Thanks,
Maggie

**Comment by staceychan** [comment]
Thanks! I'm going to close it
