### ISSUE TITLE
model.plot_evaluate_res() error

### ISSUE THREAD

**Issue by haghad** [sassoftware/python-dlpy#335]
**When I try to run:
model.plot_evaluate_res(img_type='A', randomize=True, n_images=10)
I get the following error:**

NOTE: Cloud Analytic Services dropped table TEMP_PLOT from caslib CASUSER(h-xxxxxxx@xxxxxxx.com).
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-53-d65097683505> in <module>
----> 1 model.plot_evaluate_res(img_type='A', randomize=True, n_images=10)

/usr/local/lib/python3.6/site-packages/dlpy/model.py in plot_evaluate_res(self, cas_table, img_type, image_id, filename, n_images, target, predicted_class, label_class, randomize, seed)
   1960             labels = [item.replace('_', '\n') for item in labels]
   1961 
-> 1962             plot_predict_res(image, label, labels, values)
   1963 
   1964     def get_feature_maps(self, data, label=None, idx=0, image_id=None,  **kwargs):

/usr/local/lib/python3.6/site-packages/dlpy/utils.py in plot_predict_res(image, label, labels, values)
    220     ax1.axis('off')
    221     ax2 = fig.add_subplot(1, 2, 2)
--> 222     predicted_prob_barplot(ax2, labels, values)
    223 
    224 

/usr/local/lib/python3.6/site-packages/dlpy/utils.py in predicted_prob_barplot(ax, labels, values)
    189     ax.set_xlabel('Probability')
    190     ax.set_xticks([0, 0.25, 0.5, 0.75, 1, 1.1])
--> 191     ax.set_xticklabels(['0%', '25%', '50%', '75%', '100%'])
    192     ax.set_title('Predicted Probability')
    193     return ax

/usr/local/lib64/python3.6/site-packages/matplotlib/axes/_base.py in wrapper(self, *args, **kwargs)
     61 
     62         def wrapper(self, *args, **kwargs):
---> 63             return get_method(self)(*args, **kwargs)
     64 
     65         wrapper.__module__ = owner.__module__

/usr/local/lib64/python3.6/site-packages/matplotlib/cbook/deprecation.py in wrapper(*args, **kwargs)
    449                 "parameter will become keyword-only %(removal)s.",
    450                 name=name, obj_type=f"parameter of {func.__name__}()")
--> 451         return func(*args, **kwargs)
    452 
    453     return wrapper

/usr/local/lib64/python3.6/site-packages/matplotlib/axis.py in _set_ticklabels(self, labels, fontdict, minor, **kwargs)
   1791         if fontdict is not None:
   1792             kwargs.update(fontdict)
-> 1793         return self.set_ticklabels(labels, minor=minor, **kwargs)
   1794 
   1795     @cbook._make_keyword_only("3.2", "minor")

/usr/local/lib64/python3.6/site-packages/matplotlib/axis.py in set_ticklabels(self, ticklabels, minor, **kwargs)
   1713             if len(locator.locs) != len(ticklabels) and len(ticklabels) != 0:
   1714                 raise ValueError(
-> 1715                     "The number of FixedLocator locations"
   1716                     f" ({len(locator.locs)}), usually from a call to"
   1717                     " set_ticks, does not match"

ValueError: The number of FixedLocator locations (6), usually from a call to set_ticks, does not match the number of ticklabels (5).

**I am getting this error even if I change the input values of img_type, n_images.
Also, I am using dlpy v1.2.0.
Everything else above upstream has worked fine, including calls to model.evaluate, model.fit, model.valid_conf_mat...**

**Comment by dxq77dxq** [comment]
Hello,

Would you please share your notebook? It helps us get more insight to the error.

Thanks,
Maggie

**Comment by haghad** [comment]
Actually, it says it in the stacktrace--
the call to ax.set_xticks and ax.set_ticklabels have input lists of different lengths:

/usr/local/lib/python3.6/site-packages/dlpy/utils.py in predicted_prob_barplot(ax, labels, values)
189 ax.set_xlabel('Probability')
**190 ax.set_xticks([0, 0.25, 0.5, 0.75, 1, 1.1])
--> 191 ax.set_xticklabels(['0%', '25%', '50%', '75%', '100%'])**
192 ax.set_title('Predicted Probability')
193 return ax

**Comment by eusdougc** [comment]
@haghad - This bug was fixed in #321.  Until we have a new release, you will have to clone the repo to get the fix.

**Comment by eusdougc** [comment]
@haghad - did cloning the repo resolve the issue for you?

**Comment by haghad** [comment]
> @haghad - did cloning the repo resolve the issue for you?

Thank you for your response.
Last week, I went ahead and copy/pasted the relevant functions out of utils and model.py and modified them slightly to work within the notebook.
