### ISSUE TITLE
example notebook loading file code snippet

### ISSUE THREAD

**Issue by haghad** [sassoftware/python-dlpy#339]
Hello, I have comment regarding the following notebook:
https://github.com/sassoftware/python-
dlpy/blob/master/examples/quick_start/A_Comprehensive_Image_Classification_Example.ipynb

In the code snippet below, the comment says to provide the path AND filename, however, 
in the line model_file, it says path-to server-accessible deployment-directory and doesn't explicitly point out that the filename part. 

```
# The model_file variable holds the fully-qualified server-side path 
# and file name for your deployed .sashdat model. This should be the 
# server location where you deployed the 'model3' vgg16.sashdat table.

model_file = '/path-to/server-accessible/deployment-directory/'
```

I suggest changing that line to something like the following:
```
model_file = '/path-to/server-accessible/deployment-directory/your-saved-model-file.sashdat'
```
This will make it easier for new users, as I too was caught off-guard by this for a moment.

**Comment by eusdougc** [comment]
@haghad  - I will ask our tech writer to look at your suggestion.  I think this should be fairly straightforward to include.

**Comment by eusdougc** [comment]
Example was updated in pull request #344.
