### ISSUE TITLE
Unusual bounding box 

### ISSUE THREAD

**Issue by tomstocksasinstitute** [sassoftware/python-dlpy#346]
Hello,
I have been strguggling witt the following issue: 
![image](https://user-images.githubusercontent.com/54203530/101324645-de2b4a80-386a-11eb-818a-5966c1de4b09.png)
as you can see my bounding boxes are fine, I checked hundreds visually :
![image](https://user-images.githubusercontent.com/54203530/101324754-03b85400-386b-11eb-9b77-858b50d6114d.png)
Now it is possible that some bounding boxes are very small. 
I think the parameter IgnoreTrainingError has been deprecated? 
No issue is raised when I load the data from the filesystem. 
I am trying to find which image/images are the problem. Because when I split the data, sometimes it works, so i think it is a handful of images with bounding boxes issue. I have now 6000 images, but I will load 30.000. So I need to find a way to identify them and delete those few problems. 
this is how my data looks at loading: 
![image](https://user-images.githubusercontent.com/54203530/101325115-83deb980-386b-11eb-9a91-3d3e200c2790.png)
It all worked fine with the previous version of dlpy, I run the same notebook 2years ago without problems. 
Let me know what is happenning and how i can resolve this.
Thanks
Tom;

**Comment by shlongsas** [comment]
ignoreTrainingError should still work.
You can set the logLevelto >=5, it will display the coordinate information for the problematic

**Comment by eusdougc** [comment]
@tomstocksasinstitute - did @shlongsas suggestion work for you?  Are you still having a problem?

**Comment by tomstocksasinstitute** [comment]
Yes my problem was solved.
I could not find where to use ignoreTrainingError in the optimizer. 
However, I could find the exact shape of the images that were wrong using log_level = 5 (one by one, requiring to reload each time the full dataset). So I would suggest to automatically drop the images with corrupt bounding box when resizing, maybe with a warning? or list all images with the filename that are corrupt? .
The origin is the issue is similar to the issue above, bounding boxes were generated on 768x768 images but we needed to resize to 416x416 for tiny yolo v2.
The model is now an astore and should be deployed soon. 
Thanks,
Tom.

**Comment by eusdougc** [comment]
@tomstocksasinstitute - going through the images one by one sounds painful, but I am happy to hear that you were able to resolve your issue.  For what it is worth, the parameter ignoreTrainingError is not surfaced in our DLPy APIs as it is not commonly used.  You would have to call the underlying train action directly using our low-level Python API.  Since you managed to sift out the bad images another way, we won't have to go down that particular path.

We will consider your suggestions regarding dropping images or issuing a warning.
