### ISSUE TITLE
Since there is no image that contains a bounding box, cannot display any image.

### ISSUE THREAD

**Issue by jackyyanggp** [sassoftware/python-dlpy#350]
Hi @bensloane @sasxianhu, could you please provide more details about how the issue was solved? did you change any parameters when "fitting"? I am running into the same issues. Thanks!

_Originally posted by @jackyyanggp in https://github.com/sassoftware/python-dlpy/issues/86#issuecomment-751927394_

**Comment by eusdougc** [comment]
@jackyyanggp - @bensloane and @sasxianhu  have moved on to other roles and cannot answer your question.  I read through the thread in issue #86 and it appears that the approach taken was to ensure that a small data set could be overfit.  If you model cannot overfit a small data set, then there is likely something wrong with either the data or the hyperparameters you are using for training.

**Comment by eusdougc** [comment]
Closed due to inactivity.
