### ISSUE TITLE
Different result between astore on ESP and VDMML

### ISSUE THREAD

**Issue by staceychan** [sassoftware/python-dlpy#352]
Hi Experts,

We are trying to use Astore model which create by viya VDMML to score the image on ESP Edge.
But we found that the result is a little different between ESP and VDMML predicted probability.
Cause our customer set the probability threshold to like 0.9996, it's critical if the difference higher than even 0.00001.

We want to know if there's any suggest to let the results be the same?

Thanks :)

**Comment by dxq77dxq** [comment]
Hi Stacey,
Did you apply the same data augmentation techniques to ESP and DlScore? How about other hyper-parameters such as nThread? If you can share the model and data then I can probably provide more information.
Thanks,
Maggie

**Comment by staceychan** [comment]
Hi Maggie,

Thanks for your replying! :)
Here is my code
1. Training code for dlpy
2. Scoring code on viya
3. Scoring code on ESP Edge

We just do image resizing before the model and out dataset is mnist.
To simplify the problelm, we used 'zero' and 'one' data in mnist only.

We didn't change any hyper-parameters like thread, channel means.. in both of the methods.
But we did consider maybe some default settings make theses two results different.

P.S. We also do the test on the ONNX model (deploy model by onnx and scoring by onnxruntime), the result is also different.

If there's any further information I can provide, please let me know.
Really appreciate your kindly support!!

Best,
Stacey
[
[DLpy.zip](https://github.com/sassoftware/python-dlpy/files/5793682/DLpy.zip)
](url)

**Comment by staceychan** [comment]
Hi Maggie,

Thanks for replying me by e-mail.
And we realized that it's because of different NVIDIA GPU architectures.

Best,
Stacey
