### ISSUE TITLE
How do I rename a dlpy model?

### ISSUE THREAD

**Issue by haghad** [sassoftware/python-dlpy#353]
I have successfully loaded a model that was previously saved, and I called get_model_info() to see the 'Model Name', as in the screenshot below.

![modelinfo](https://user-images.githubusercontent.com/44681869/105080984-98fc5a00-5a5f-11eb-9d02-b2b5d2525ffd.png)

I need to rename the model, but nothing I've tried so far has worked.  Can someone please provide the code needed to rename the model?  Thanks so much.

**Comment by dxq77dxq** [comment]
The parameter model_name is optional when creating a pre-defined model using DLPy API. Once specified, it becomes the hash key for saving/loading model attributes and parameters. Currently we don't have any function that can change the name. Closing issue.
