### ISSUE TITLE
Add examples for entity embedding

### ISSUE THREAD

**Issue by biruk23eth** [sassoftware/python-dlpy#36]
entity embedding is one of the effective methods to featurize high cardinality variables. This is especially important in the AutoML space. It will be very useful to have an example using dlpy (scores of them using e.g. tensorflow are available online).

**Comment by ethem-kinginthenorth** [comment]
@biruk23eth would you care to contribute?

**Comment by biruk23eth** [comment]
I will (down the line - loaded now). But  in case somebody wants to do it sooner, it will be great.

**Comment by ethem-kinginthenorth** [comment]
I am assigning this to you, thanks.

**Comment by sasxianhu** [comment]
We do not support trainable embedding yet until Viya 3.5
