### ISSUE TITLE
Pretrained huggingface models

### ISSUE THREAD

**Issue by anttiheino** [sassoftware/python-dlpy#361]
When specifying a huggingface model, only the models starting with bert-, roberta- and distil- are supported. However, it would enable users to develop models for other languages as well if that restriction was removed. For example, the Finnish model is similar size to bert-uncased, but its name starts with "TurkuNLP/bert" so it cannot be used yet.
![berterror](https://user-images.githubusercontent.com/81144914/111951230-0bcf9300-8aec-11eb-8982-7ead98297a90.PNG)

**Comment by eusdougc** [comment]
Hi @anttiheino  - we will take a look at the problem and assess the difficulty of the required fix.

**Comment by eusdougc** [comment]
@anttiheino - you can now clone the master branch and pick up the fix.
