### ISSUE TITLE
Load model from astore?

### ISSUE THREAD

**Issue by jlwalke2** [sassoftware/python-dlpy#366]
Is there a way to load a model from an astore file?  Or convert an astore loaded in CAS into a Model instance?

It's easy to go from a Model to an astore with `dlpy.Model.save_to_astore()` but there doesn't appear to be a `dlpy.Model.from_astore()`.

**Comment by eusdougc** [comment]
@jlwalke2  and I communicated offline.  The main question here is this: the Model class has a number of user-friendly features, like .predict(), .plot_evaluate_res(), .heat_map_analysis(), etc.  I’m trying to figure out if saving the model as an ASTORE prevents me from using these features down the road.

The short answer to this question is yes.  Once a model has been saved in ASTORE format, you cannot use the Model interface with it.  That could be a new feature request, although there are some Model interfaces that would not be supported.

**Comment by jlwalke2** [comment]
thanks @eusdougc
