### ISSUE TITLE
BERT_Model name parameter casing

### ISSUE THREAD

**Issue by anttiheino** [sassoftware/python-dlpy#367]
When trying to use pretrained huggingface models for BERT training, there is a problem that prevents the use of some pretrained models. It seems that the BERT_Model name parameter forces any text to be converted to lower case. When trying to use e.g. "TurkuNLP/bert-base-finnish-uncased-v1" model the name is converted to lower case. However, in the Huggingface website, the urls are case sensitive so the config file cannot be found with the lower case model name. 

![Bert_config_url_error](https://user-images.githubusercontent.com/81144914/116409943-feb96880-a83c-11eb-9baf-44af8bebb073.jpg)
![Config_cased_url_works](https://user-images.githubusercontent.com/81144914/116410020-0da01b00-a83d-11eb-941e-76b318c0cfb4.png)

**Comment by eusdougc** [comment]
This issue should now be resolved with pull request #370
