### ISSUE TITLE
Data Message Handlers not supported error while loading BERT when using HTTP/HTTPS Protocol

### ISSUE THREAD

**Issue by hamiz-ahmed** [sassoftware/python-dlpy#368]
Hi,
I am trying to load BERT but running into the following issue.

![image](https://user-images.githubusercontent.com/21131088/116410451-15f45800-a835-11eb-8fed-56fd73ffe01d.png)

According to my understanding, seems like that this error is resulting because **protocol=”https”** during the creation of connection in cell 2. However, I tried to change to **protocol=”cas”** but that resulted in a connection error for me.

Is this a bug or the BERT only supports binary protocol with CAS?

**Comment by eusdougc** [comment]
@hamiz-ahmed - our DLPy wrapper for BERT relies on data message handlers.  Therefore, your only option is to use protocol="cas".  This is not a bug.
