### ISSUE TITLE
timeseries_accumulation requires SAS Econometrics or SAS Visual Forecasting

### ISSUE THREAD

**Issue by CyrusBradford** [sassoftware/python-dlpy#372]
The [timeseries_accumulation](https://sassoftware.github.io/python-dlpy/generated/dlpy.timeseries.TimeseriesTable.timeseries_accumlation.html#dlpy.timeseries.TimeseriesTable.timeseries_accumlation) utility makes use of the [timeData action set](http://documentation.sas.com/?cdcId=pgmsascdc&cdcVersion=9.4_3.5&docsetId=casactecon&docsetTarget=casactecon_timedata_toc.htm).

While that action set requires either SAS Econometrics or SAS Visual Forecasting, neither is in the list of python-dlpy [prerequisites](https://github.com/sassoftware/python-dlpy#prerequisites).

**Comment by dxq77dxq** [comment]
Hi Cyrus,
List of prerequisites has been updated. Closing issue.
