### ISSUE TITLE
ImageTable.random_mutations

### ISSUE THREAD

**Issue by staceychan** [sassoftware/python-dlpy#374]
Hi Experts,

We were trying to do the random mutations on the ImageTable, but found the error messages as below.
![image](https://user-images.githubusercontent.com/35584966/125811028-87e13abf-7533-46ca-a550-6461bd817fb7.png)

It seems there's something wrong in the random_mutation function.
Here is my code

`test = pecxr_final_train.random_mutations(color_jitter=False, color_shift=False, darken=True, horizontal_flip=True, invert_pixels=False, lighten=True, sharpen=True, vertical_flip=False, inplace=False)`

If I did anything wrong, please let me know, thanks!

**Comment by dxq77dxq** [comment]
Hi Stacey,

Are you using the latest version of DLPy? This bug was fixed by a push on December 2020.

**Comment by staceychan** [comment]
Hi Expert,

Thanks for the information!
I used `pip install sas-dlpy -y` to update and found the version is 1.2.0.

After trying to download the zip and add to the system path, I realized the version is 1.2.0-dev. And the issue gone.

Many thanks :)
