### ISSUE TITLE
Save semantic segmentation predictions as .png

### ISSUE THREAD

**Issue by cshruti87** [sassoftware/python-dlpy#375]
Hello Experts,

I am doing Semantic Segmentation using SAS DLPy UNET model for which I referred the example notebook posted on this github page.
Now I have a trained model saved as .sashdat and I load it and am trying to use it for completely new out of the box data. I used model.predict which gives output in the form of CAS table. 
But I want to check the results by displaying and saving the images (predicted outputs). Is there a pre-available function to do that in utils or is there an easy way to accomplish this task?

Thanks in advance!

**Comment by dxq77dxq** [comment]
Hello,

display_segmentation_results can display the predicted images. While there are no pre-defined APIs that can save predicted images to disk, you can convert the predicted images to np array and use opencv to save them as PNGs.
