### ISSUE TITLE
Error Importing Keras h5 model 

### ISSUE THREAD

**Issue by MsJellyKing** [sassoftware/python-dlpy#378]
Hi, 

I am trying to import a Keras cnn model and receiving the below error.

**code :**
model1,use_gpu = dlpy.Model.from_keras_model(conn=sess,
                                        keras_model=keras_test, 
                                        output_model_table='converted_keras_model'
                                       )

**Error:** 
ImportError: cannot import name 'preprocess_weights_for_loading' from 'keras.engine.saving' (/opt/conda/lib/python3.8/site-packages/keras/engine/saving.py)

dlpy version 1.2
keras version 2.6

Could this be a version compatibility issue?

Thanks

**Comment by dxq77dxq** [comment]
It could be. Would you please try the dev version of dlpy? (git clone and add sys.path instead of pip install)

**Comment by MsJellyKing** [comment]
I have cloned the dev version and reran the code.
I now get a different error. Please see below:
![error1](https://user-images.githubusercontent.com/40829100/160188595-9c937c66-f074-4602-a769-a12f42f5d414.png)

**Comment by dxq77dxq** [comment]
This error message is from Keras, not DLPy. The function get_config() returns a Python dict that contains the configuration of the layer. Looks like something went wrong with the layer itself.
