### ISSUE TITLE
Darknet_Reference_Weights.sashdat not present in Obj_Det_Soccer_Weights.zip

### ISSUE THREAD

**Issue by skipsmith** [sassoftware/python-dlpy#387]
The example object detection notebook SimpleObjectDetection.ipynb refers to a zip file named Obj_Det_Soccer_Weights.zip in order to get the **file Darknet_Reference_Weights.sashdat**.  However, the zip file does not contain this file.  It only contains VGG16_YOLO_Attr_Full_Labels.sashdat and VGG16_YOLO_Weight_Attr_Label.sashdat.

**Comment by dxq77dxq** [comment]
We'll update the zip file and let you know.

**Comment by dxq77dxq** [comment]
The zip file is updated.

**Comment by skipsmith** [comment]
Thank you!  I see the zip file has the Darknet_Reference.sashdat now! 

However, the zip file is now missing the two files I mentioned in the original post (VGG16_YOLO_Attr_Full_Labels.sashdat and VGG16_YOLO_Weight_Attr_Label.sashdat).  Your FasterRCNN_Soccer.ipynb example will need those files.

**Comment by skipsmith** [comment]
Thanks! The file looks good now.
