### ISSUE TITLE
source data for examples

### ISSUE THREAD

**Issue by bensloane** [sassoftware/python-dlpy#39]
Can we host source data (sample images, astore, weights, etc) for the examples. Similar to what was done [here](https://support.sas.com/documentation/prod-p/vdmml/zip/index.html ).

**Comment by ethem-kinginthenorth** [comment]
we already have some data under test/datasources for unittests to run.
for the pre-trained weights will be on that link. 
we prefer to provide links for the large datasets rather than hosting them.
is there anything particular, you want to see?

**Comment by bensloane** [comment]
Mostly just the pretrained weights (ex 'train_less100_yolo_416.sashdat') which would make sense on the linked page above.

**Comment by ethem-kinginthenorth** [comment]
we are training a yolo v2 model and whenever it is ready, we will be adding it to that link.

**Comment by bensloane** [comment]
Great! thanks Ethem will close out.
