### ISSUE TITLE
mztrain.yaml and mzscore.yaml not provided

### ISSUE THREAD

**Issue by jlwalke2** [sassoftware/python-dlpy#390]
mzmodel.py:393 tries to read mztrain.yaml from the package directory, but the yaml file does not appear to be included in the repo.  There's a similar reference to mzscore.yaml.

**Comment by dxq77dxq** [comment]
Did you git clone the entire repository? https://github.com/sassoftware/python-dlpy/tree/master/dlpy I can see they were uploaded here.

**Comment by jlwalke2** [comment]
`pip install git+https://github.com/sassoftware/python-dlpy.git`

**Comment by dxq77dxq** [comment]
Pip install won't include the latest changes after the release. Would you please uninstall and git clone the entire repo to your local, and sys.path.append('path_to_the_repo')?

**Comment by dxq77dxq** [comment]
Fixed by https://github.com/sassoftware/python-dlpy/pull/391.
