### ISSUE TITLE
import dlpy using "is" syntax instead of "=="

### ISSUE THREAD

**Issue by elebersole** [sassoftware/python-dlpy#397]
Using SWAT with dlpy and running this code from an old program:

import swat
portnumber=30570
sess = swat.CAS('server.demo.sas.com', portnumber, 'Student', 'Metadata0', caslib="casuser")
sess
import dlpy
from dlpy import Model, Sequential
from dlpy import images, ImageTable
from dlpy import Sequential, Sequential
from dlpy import layers, Layer, InputLayer, Conv2d, Pooling, Dense, Recurrent, BN, Res, Concat, Proj, OutputLayer
from dlpy.applications import *
dlpy.__version__

I received the following error:  /opt/conda/lib/python3.10/site-packages/dlpy/utils.py:2739: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if task is 'image_classification':

**Comment by elebersole** [comment]
<img width="469" alt="2023-05-30" src="https://github.com/sassoftware/python-dlpy/assets/22181504/0ae0fd02-ad2c-4f25-a3a6-8186f686aa45">

**Comment by dxq77dxq** [comment]
Hi Beth,
MutableMapping is moved to collections.abc and is fixed by https://github.com/sassoftware/python-dlpy/pull/389. Please update your dlpy version so this fix is caught.

**Comment by myuser-git** [comment]
I have the same issue with Python 3.10 and dlpy 1.2.0, which I believe is the latest version for dlpy. Does #389 refer to it?

**Comment by dxq77dxq** [comment]
> I have the same issue with Python 3.10 and dlpy 1.2.0, which I believe is the latest version for dlpy. Does #389 refer to it?

Please install the dev version: pip install git+https://github.com/sassoftware/python-dlpy.git
