### ISSUE TITLE
SimpleObjectDetection required column does not exist in table

### ISSUE THREAD

**Issue by crack3n-collab** [sassoftware/python-dlpy#403]
So in the simpleObjectDetection example when the Soccer_Images_416.sashdat is converted to a CAStable. It has this amount of columns
![image](https://github.com/sassoftware/python-dlpy/assets/82193366/9099f614-a9dd-4376-9051-5a077a6fdc69)
later the soccer data is then split into trainset and testset and there's no issues.

So I tried using my own data and these are the columns
![image](https://github.com/sassoftware/python-dlpy/assets/82193366/b86bb878-1250-414b-b0fb-15d859fa1f88)
it's drastically different from soccer data and so I had trouble splitting it into trainset and testset in the later part of the code.
![image](https://github.com/sassoftware/python-dlpy/assets/82193366/e443f8b4-73df-46bb-8393-38a2a3bf8828)
I understand my data columns are incorrect but is there a correct way to generate those missing required columns?
https://github.com/sassoftware/python-dlpy/blob/master/examples/object_detection/SimpleObjectDetection.ipynb

**Comment by crack3n-collab** [comment]
I generated my CASTable using code from https://github.com/michaelgorkow/SAS_DeepLearning/blob/master/Face_Mask_Detection/image_augmentation_object_detection.ipynb . 
![image](https://github.com/sassoftware/python-dlpy/assets/82193366/61dd0242-6a2a-4d61-a588-29db61d980c6)

I do know that in simpleOjectDetection, there's also a [PrepareObjectDetectionTable.ipynb](https://github.com/sassoftware/python-dlpy/blob/master/examples/object_detection/PrepareObjectDetectionTable.ipynb) but it seems to require xml data which I don't have.

**Comment by dxq77dxq** [comment]
Please add "im_table=False" to your two_way_split().

**Comment by crack3n-collab** [comment]
im_table = false sets the CASTables to be returned with all columns so they're not imagetables. In the later part of the code, it says the image table is created from the training table. But it still able to create the table so how does that work?
![image](https://github.com/sassoftware/python-dlpy/assets/82193366/4c06710b-b6a1-4c1b-b014-70c13493d9ec)

**Comment by dxq77dxq** [comment]
Cells 10-14 are for summary and visualization. You don't really need them for training and scoring. You can directly what you get from two_way_split() for traning.

**Comment by crack3n-collab** [comment]
What are you referring to when you say cells 10-14?

**Comment by dxq77dxq** [comment]
https://github.com/sassoftware/python-dlpy/blob/master/examples/object_detection/SimpleObjectDetection.ipynb

**Comment by crack3n-collab** [comment]
Oh ok, I understand what you're referring to now. It's indeed for summary and visualization. So error message won't affect much, would it? Since in the end the tables are still generated

**Comment by dxq77dxq** [comment]
The error is from here: https://github.com/sassoftware/python-dlpy/blob/master/dlpy/images.py#L207

I would suggest you skip it and move to training directly.

**Comment by crack3n-collab** [comment]
So the split of the table into trainset and testset can be skipped?

**Comment by dxq77dxq** [comment]
I'll suggest you keep it so you can use different datasets for training and scoring. Please let me know if you questions are resolved and I'll close the issue.

**Comment by crack3n-collab** [comment]
I have run through the whole code successfully and you can close this issue. Thank you very much for the help.
