### ISSUE TITLE
Issue with YOLOv2 model training 

### ISSUE THREAD

**Issue by neelan29** [sassoftware/python-dlpy#46]
I am trying to train a tiny yolov2 model on a very small dataset. I have defined the model DAG and did the training as well using pre-trained weights from Darknet model. However, I face issues when I try to score the model. I am scoring the model on training set but face an error which I am unable to resolve.

This is the issue:
![image](https://user-images.githubusercontent.com/23342589/49036721-783d6000-f186-11e8-9a0b-3dceec81e4d9.png)

Any suggestions on resolving this issue?

Thanks!!

**Comment by neelan29** [comment]
I trained the model on "trainset" and thats where I do the predictions as well. The training runs successfully however, it doesnt process the same set of images for scoring. What could be the issue here? Could you suggest trying something?

**Comment by ethem-kinginthenorth** [comment]
Scoring the training set does not guarantee that you would detect the objects.
