### ISSUE TITLE
Loading model from sashdat meets error.

### ISSUE THREAD

**Issue by jackhu3301** [sassoftware/python-dlpy#6]
model3 = Model.from_sashdat(conn = s, path='/home/sas/DEMO/driver_image/data_scripts/vgg/VGG16_model.sashdat')

It tells me that :

ERROR: The caslib Caslib_qErNjR is a duplicate, parent or subpath of caslib Caslib_Eutm6c.
ERROR: Could not add caslib 'Caslib_qErNjR'. Make sure that the caslib does not already exist and that you have permissions to add caslibs to Cloud Analytic Services.
ERROR: The action stopped due to errors.
ERROR: The caslib 'Caslib_qErNjR' does not exist in this session.
ERROR: The action stopped due to errors.
ERROR: The file or path 'Model_bwlxjJ' is not available in the file system.
ERROR: Table 'Model_bwlxjJ' could not be loaded.
ERROR: Failure opening table 'Model_bwlxjJ': A table could not be loaded.
ERROR: The action stopped due to errors.

What should I do?

**Comment by bensloane** [comment]
I will try and reproduce. Can you provide this file so I can test.

**Comment by sasxianhu** [comment]
This usually means your path /home/sas/DEMO/driver_image/data_scripts/vgg is already used in a caslib.

You can copy you sashdat to a new directory and give it a try.

Best,
XQ

On May 16, 2018, at 6:11 AM, Ben Sloane <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

I will try and reproduce. Can you provide this file so I can test.

**Comment by bensloane** [comment]
You can see your current caslib for connection by running the .caslibinfo() action. Most likely you have this path as a caslib already as stated above. I would try moving the file to a seperate directory and running the method again. See attachment for example. 
[from_sashdat (1).zip](https://github.com/sassoftware/python-dlpy/files/2009000/from_sashdat.1.zip)
