### ISSUE TITLE
support tabular data

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [sassoftware/python-dlpy#64]

**Comment by ethem-kinginthenorth** [comment]
@RLstat I am assuming we are supporting tabular data now, right?

**Comment by RLstat** [comment]
@ethem-kinginthenorth , yes, we are. I've included examples about how to use dlpy for tabular data analysis.

**Comment by ethem-kinginthenorth** [comment]
@RLstat thanks. closing the issue
