### ISSUE TITLE
model.save_to_table and _with_caslibify doesn't actually save a file containing a table

### ISSUE THREAD

**Issue by TheodorGosden** [sassoftware/python-dlpy#75]
After i execute `model1.save_to_table("/media")` there's nothing in the /media folder on the server. Even though I get this output:

```
model1.save_to_table("/media")
NOTE: Model table saved successfully.
```

**Comment by ethem-kinginthenorth** [comment]
if you are not getting any errors, you should debug your code and see what is happening. It is quite hard from here to comment. But again, I am thinking there might something related with caslibs.

**Comment by ethem-kinginthenorth** [comment]
I just check the code again. The current code expects you to have some weights (means training) then you can save model file as well as weights. Closing this as nobug.

**Comment by sasxianhu** [comment]
If model1 does not contain any weight, shouldnt we return the error when trying to save them as CAS tables?

**Comment by ethem-kinginthenorth** [comment]
I am leaving that part to the user. If we cannot save the table due to an error we do give proper messages but we just don't let users to save a model only table.
