### ISSUE TITLE
problem with display_object_detections

### ISSUE THREAD

**Issue by mdziec** [sassoftware/python-dlpy#82]
This code:
display_object_detections(sess, 'tbl', 'yolo', max_objects=3, num_plot=3, n_col=2)
ends with error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-a9a6b0fe6733> in <module>()
----> 1 display_object_detections(sess, 'tbl', 'yolo', max_objects=3, num_plot=3, n_col=2)

/home/sasdemo/.local/lib/python3.6/site-packages/dlpy/utils.py in display_object_detections(conn, table, coord_type, max_objects, num_plot, n_col, fig_size)
   1336     det_label_image_table = random_name('detLabelImageTable')
   1337 
-> 1338     num_max_obj = input_table['_nObjects_'].max()
   1339     max_objects = max_objects if num_max_obj > max_objects else num_max_obj
   1340 

/home/sasdemo/.local/lib/python3.6/site-packages/swat/cas/table.py in max(self, axis, skipna, level, casout, **kwargs)
   9688 
   9689         out = self._topk_values('max', axis=axis, skipna=skipna, level=level,
-> 9690                                 **kwargs)
   9691 
   9692         if self.get_groupby_vars():

/home/sasdemo/.local/lib/python3.6/site-packages/swat/cas/table.py in _topk_values(self, stats, axis, skipna, level, numeric_only, leave_index, **kwargs)
   4224                 minmax.dropna(inplace=True)
   4225             if 'min' not in stats:
-> 4226                 minmax = minmax.set_index('stat').drop('min').reset_index()
   4227             if 'max' not in stats:
   4228                 minmax = minmax.set_index('stat').drop('max').reset_index()

/opt/sasinside/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py in drop(self, labels, axis, level, inplace, errors)
   1905                 new_axis = axis.drop(labels, level=level, errors=errors)
   1906             else:
-> 1907                 new_axis = axis.drop(labels, errors=errors)
   1908             dropped = self.reindex(**{axis_name: new_axis})
   1909             try:

/opt/sasinside/anaconda3/lib/python3.6/site-packages/pandas/indexes/base.py in drop(self, labels, errors)
   3260             if errors != 'ignore':
   3261                 raise ValueError('labels %s not contained in axis' %
-> 3262                                  labels[mask])
   3263             indexer = indexer[~mask]
   3264         return self.delete(indexer)

ValueError: labels ['min'] not contained in axis

Any idea?

**Comment by mdziec** [comment]
Source of the problem is in **create_object_detection_table**! 
If filename contains dots ("aaa.sss.bbb.png" and "aaa.sss.bbb.xml") then result table have missing values in almost all columns.

**Comment by ethem-kinginthenorth** [comment]
Sounds like a bug. @wenyushi can you please take a look at this.

**Comment by ethem-kinginthenorth** [comment]
Thanks @mdziec for identifying the problem.
