### ISSUE TITLE
missing doc string for a couple of parameters in Tiny_Yolov2 model

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [sassoftware/python-dlpy#83]
I have a question about Tiny_YoloV2() function of DLPy1.0.
In the following sample code of object detection on github,
  https://github.com/sassoftware/python-dlpy/blob/master/examples/object_detection/SimpleObjectDetection.ipynb
the following are described as parameters of Tiny_YoloV2 () function,
yolo_model = Tiny_YoloV2(s,
n_classes=2,
predictions_per_grid=5,
anchors = yolo_anchors,
max_boxes=100,
coord_type='yolo',
max_label_per_image = 100,
class_scale=1.0,
coord_scale=1.0,
prediction_not_a_object_scale=1,
object_scale=5,
detection_threshold=0.2,
iou_threshold=0.2)
However,
The following parameters are not explained in the following API document.
class_scale=1.0,
coord_scale=1.0,
prediction_not_a_object_scale=1,
object_scale=5,
detection_threshold=0.2,
iou_threshold=0.2
sassoftware.git...ons.Tiny_YoloV2
Where is the document describing these parameters?

**Comment by ethem-kinginthenorth** [comment]
@wenyushi can you please also look at this one

**Comment by wenyushi** [comment]
Those parameters are documented in detection layer. I will update the document.

**Comment by ethem-kinginthenorth** [comment]
Thanks @wenyushi
