### ISSUE TITLE
APIs for model assessments

### ISSUE THREAD

**Issue by sasxianhu** [sassoftware/python-dlpy#87]
Wrappers for the assess action for regression and classification models.

**Comment by ethem-kinginthenorth** [comment]
@sasxianhu could you please elaborate on these a little bit. Thanks

**Comment by sasxianhu** [comment]
https://scikit-learn.org/0.17/modules/model_evaluation.html#classification-metrics
https://scikit-learn.org/0.17/modules/model_evaluation.html#regression-metrics

We have actions to do all these but better provide more friendly APIs.

**Comment by ethem-kinginthenorth** [comment]
There is already an issue: #59 . I am keeping this as it is more detailed and closing the other one.

**Comment by RLstat** [comment]
I will start working on the classification metrics shortly if no one has taken it.

**Comment by ethem-kinginthenorth** [comment]
@RLstat any progress on this end?

**Comment by RLstat** [comment]
@ethem-kinginthenorth I finished the metrics and doc, but still working on some unit tests. Will send merge request probably Monday when more tests are added.

**Comment by ethem-kinginthenorth** [comment]
Awesome. thanks for the update, @RLstat

**Comment by ethem-kinginthenorth** [comment]
@RLstat, would the new merge resolves this issue?

**Comment by RLstat** [comment]
@ethem-kinginthenorth , I will close it once I update the examples and demonstrate some of the newly added functionalities.

**Comment by ethem-kinginthenorth** [comment]
@RLstat, great. thanks

**Comment by ethem-kinginthenorth** [comment]
@RLstat I believe you have the examples for this right?

**Comment by RLstat** [comment]
@ethem-kinginthenorth , yes, the examples are included in the tabular data analysis, so we can close this one now.

**Comment by ethem-kinginthenorth** [comment]
@RLstat thanks. closing the issue
