### ISSUE TITLE
DLPyError: Detection data contains classes that are not in ground truth

### ISSUE THREAD

**Issue by mdziec** [sassoftware/python-dlpy#93]
If all class names are shorter than 8 characters then until _Object0_ is fully completed, the evaluate_object_detection method returns an error because the "NoObject" constant is truncated in the detection table.

Part of the prediction table: 

idjoin | _Object0_ | _Object1_ | _Object2_ | _Object3_ | _Object4_ | _Object5_ | _Object6_
-- | -- | -- | -- | -- | -- | -- | --
8ancj8j8a1_1 | NoObjec | NoObjec | NoObjec | NoObjec | NoObjec | NoObjec | NoObjec
8ancau3g71_1 | NoObjec | NoObjec | NoObjec | NoObjec | NoObjec | NoObjec | NoObjec
8ancbnt251_1 | NoObjec | NoObjec | NoObjec | NoObjec | NoObjec | NoObjec | NoObjec
8anco14t91_1 | NoObjec | NoObjec | NoObjec | NoObjec | NoObjec | NoObjec | NoObjec
8anccg8s21_1 | noz | noz | noz | noz | noz | noz | NoObjec

Part of the training table:

idjoin | _Object0_ | _Object1_ | _Object2_ | _Object3_ | _Object4_ | _Object5_ | _Object6_
-- | -- | -- | -- | -- | -- | -- | --
8ancj8j8a1_1 | proszek | noz | noz |   |   |   |  
8ancau3g71_1 | proszek | noz | noz |   |   |   |  
8ancbnt251_1 | piasek | butelka |   |   |   |   |  
8anco14t91_1 | piasek | noz |   |   |   |   |  
8anccg8s21_1 | noz | noz | noz | noz | noz | piasek | noz

metrics = model.evaluate_object_detection(ground_truth=dettbl, coord_type='yolo',
                                               classes=klasy, iou_thresholds=0.5)

---------------------------------------------------------------------------
DLPyError                                 Traceback (most recent call last)
<ipython-input-121-78f29dc03f5a> in <module>()
      1 metrics = model.evaluate_object_detection(ground_truth=dettbl, coord_type='yolo',
      2                                                classes=klasy,
----> 3                                                iou_thresholds=0.5)

/home/sasdemo/.local/lib/python3.6/site-packages/dlpy/model.py in evaluate_object_detection(self, ground_truth, coord_type, detection_data, classes, iou_thresholds)
   1298         classes_not_detected = [x for x in classes_gt if x not in classes]
   1299         if len([x for x in classes if x not in classes_gt]) > 0:
-> 1300             raise DLPyError('Detection data contains classes that are not in ground truth')
   1301 
   1302         if not isinstance(iou_thresholds, collections.Iterable):

DLPyError: Detection data contains classes that are not in ground truth

**Comment by wenyushi** [comment]
Hi, I believe the issue has been fixed in the DLPy 1.0.1 version. Can you update it and see if it works?

**Comment by mdziec** [comment]
I did an update but I have not checked if everything is OK.

**Comment by ethem-kinginthenorth** [comment]
I am closing this one up due to inactivity. Please do open it back if you need to
