### ISSUE TITLE
Model.deploy() where clause 

### ISSUE THREAD

**Issue by bensloane** [sassoftware/python-dlpy#98]
Related to #94 . Using model.deploy() with castable as the output_format. Receive a dlpy error stating something is wrong while extracting model attributes. See below for example used and error message. Would I just save attributes, weights, model table separately? We can also move this to #94 if this shouldn't be a separate issue. Thanks!

### Example
Model training
```python
solver = MomentumSolver(learning_rate=0.001, learning_rate_policy='MULTISTEP', 
                        steps=[30, 50, 70], clip_grad_max = 100, clip_grad_min = -100)
optimizer = Optimizer(algorithm=solver, mini_batch_size=8, log_level=2, max_epochs=80, reg_l2=0.0005)
data_specs = [DataSpec(type_='IMAGE', layer='Input1', data=inputVars),
              DataSpec(type_='OBJECTDETECTION', layer='Detection1', data=targets)]
gpu = Gpu(devices=[0, 1, 2, 3])
yolo_darknet.model_weights = s.CASTable('Darknet_weights', where = '_layerid_<42')
yolo_darknet.fit(data=train, 
          valid_table=valid,
          optimizer=optimizer, 
          data_specs=data_specs, 
          n_threads=16, 
          record_seed = 13309,
          force_equal_padding=True, 
          gpu= gpu
         )
```
Model deployment
```python
yolo_darknet.deploy('path', output_format='table')
```

### Error message
ERROR: Parameter 'where' is not recognized.
ERROR: Expecting one of the following: task, caslib, name, table, xml, xmlPath, set, attributes, attrTable, attrs.
ERROR: The action stopped due to errors.

DLPyError                                 Traceback (most recent call last)
<ipython-input-26-a73f7ec992d4> in <module>()
----> 1 yolo_darknet.deploy('path',  output_format='table')

/opt/conda/lib/python3.6/site-packages/dlpy/model.py in deploy(self, path, output_format, model_weights, **kwargs)
   2547             self.save_to_astore(path=path, **kwargs)
   2548         elif output_format.lower() in ('castable', 'table'):
-> 2549             self.save_to_table(path=path)
   2550         elif output_format.lower() == 'onnx':
   2551             self.save_to_onnx(path, model_weights=model_weights)

/opt/conda/lib/python3.6/site-packages/dlpy/model.py in save_to_table(self, path)
   2333 
   2334         """
-> 2335         self.save_to_table_with_caslibify(path)
   2336         """dir_name, file_name = os.path.split(path)
   2337 

/opt/conda/lib/python3.6/site-packages/dlpy/model.py in save_to_table_with_caslibify(self, path)
   2417                     for msg in rt.messages:
   2418                         print(msg)
-> 2419                     raise DLPyError('something is wrong while extracting the model attributes!')
   2420 
   2421                 rt = self._retrieve_('table.save', table=CAS_tbl_name, name=attr_tbl_file, replace=True, caslib=caslib)

DLPyError: something is wrong while extracting the model attributes!

**Comment by bensloane** [comment]
This was a user error on my part. My model and weights table are both 23 layers, rather then the larger YoloV2 architecture of 43 layers.  I was able to deploy by changing the where clause. I successfully ran deploy() by changing the where clause in the weight assignment. 

``` python
yolo_darknet.model_weights = s.CASTable('Darknet_weights', where = '_layerid_<21')
```
 Can be closed.

**Comment by ethem-kinginthenorth** [comment]
glad it worked out. closing per owner's request.
